CREATE VIEW omd_reporting.vw_EXCEPTIONS_DISABLED_PROCESSES AS
--Show which modules haven't run in the last 60 days
SELECT
    MODULE_ID,
    MODULE_CODE,
    'Module' AS CLASSIFICATION,
    FREQUENCY_CODE,
    MODULE_DESCRIPTION AS ADDITIONAL_INFORMATION
FROM omd.MODULE WHERE ACTIVE_INDICATOR = 'N'
UNION ALL
SELECT
    BATCH_ID,
    BATCH_CODE,
    'Batch' AS CLASSIFICATION,
    FREQUENCY_CODE,
    BATCH_DESCRIPTION AS ADDITIONAL_INFORMATION
FROM omd.BATCH WHERE ACTIVE_INDICATOR = 'N'
  UNION ALL
SELECT
    batchmod.MODULE_ID,
    module.MODULE_CODE,
    'Module, disabled at Batch/Module level' AS CLASSIFICATION,
    'Not applicable' AS FREQUENCY_CODE,
    'Disabled within Batch ''' + batch.BATCH_CODE + ''' with Batch ID ' + CONVERT(NVARCHAR(10),batchmod.BATCH_ID )
FROM omd.BATCH_MODULE batchmod
JOIN omd.MODULE module ON batchmod.MODULE_ID=module.MODULE_ID
JOIN omd.BATCH batch ON batchmod.BATCH_ID=batch.BATCH_ID
WHERE batchmod.ACTIVE_INDICATOR = 'N'
