CREATE VIEW [omd_reporting].[vw_EXECUTION_LOG_BATCH_INSTANCE]
AS

SELECT
    BI.BATCH_INSTANCE_ID
  , B.BATCH_CODE
  , BI.EXECUTION_CONTEXT
  , BI.START_TIMESTAMP
  , BI.END_TIMESTAMP
  , DATEDIFF(second, BI.START_TIMESTAMP, BI.END_TIMESTAMP) AS EXECUTION_TIME
  --, CAST (CAST ((BI.END_TIMESTAMP - BI.START_TIMESTAMP) AS TIME) AS NVARCHAR (30)) AS EXECUTION_TIME
  , PIND.INTERNAL_PROCESSING_STATUS_CODE_DESCRIPTION
  , NR.NEXT_RUN_DESCRIPTION
  , BI.EXECUTION_STATUS_CODE
  , ES.EXECUTION_STATUS_DESCRIPTION
FROM
  [omd].[BATCH_INSTANCE] BI
  INNER JOIN [omd].[BATCH] B ON BI.BATCH_ID = B.BATCH_ID
  INNER JOIN [omd_metadata].[INTERNAL_PROCESSING_STATUS] PIND ON BI.INTERNAL_PROCESSING_CODE = PIND.INTERNAL_PROCESSING_STATUS_CODE
  INNER JOIN [omd_metadata].[NEXT_RUN_STATUS] NR ON BI.NEXT_RUN_STATUS_CODE = NR.NEXT_RUN_STATUS_CODE
  INNER JOIN [omd_metadata].[EXECUTION_STATUS] ES ON BI.EXECUTION_STATUS_CODE = ES.EXECUTION_STATUS_CODE
WHERE
  BATCH_INSTANCE_ID <> 0
