CREATE TABLE [omd].[MODULE] (
  [MODULE_ID]           INT IDENTITY (1, 1)             NOT NULL,
  [MODULE_CODE]         NVARCHAR (1000)                 NOT NULL,
  [MODULE_TYPE]         NVARCHAR (100)                  NOT NULL,
  [DATA_OBJECT_SOURCE]  NVARCHAR (1000)                 NULL,
  [DATA_OBJECT_TARGET]  NVARCHAR (1000)                 NULL,
  [AREA_CODE]           NVARCHAR (100)                  NOT NULL,
  [FREQUENCY_CODE]      NVARCHAR (100)
    CONSTRAINT [DF_OMD_MODULE_FREQUENCY_CODE]
    DEFAULT (N'On-demand')                              NOT NULL,
  [ACTIVE_INDICATOR]    CHAR (1)
    CONSTRAINT [DF_OMD_MODULE_ACTIVE_INDICATOR]
    DEFAULT ('Y')                                       NOT NULL,
  [MODULE_DESCRIPTION]  NVARCHAR (4000)                 NULL,
  [EXECUTABLE]          NVARCHAR (MAX)                  NULL,

  CONSTRAINT [PK_OMD_MODULE]
    PRIMARY KEY CLUSTERED ([MODULE_ID] ASC),

  CONSTRAINT [IX_OMD_MODULE_MODULE_CODE]
    UNIQUE NONCLUSTERED ([MODULE_CODE] ASC),

  CONSTRAINT [FK_OMD_MODULE_OMD_METADATA_AREA]
    FOREIGN KEY ([AREA_CODE])
    REFERENCES [omd_metadata].[AREA] ([AREA_CODE]),

  CONSTRAINT [FK_OMD_MODULE_OMD_METADATA_FREQUENCY]
    FOREIGN KEY ([FREQUENCY_CODE])
    REFERENCES [omd_metadata].[FREQUENCY] ([FREQUENCY_CODE])
);
