CREATE TABLE [omd].[MODULE_INSTANCE_EXECUTED_CODE] (
  [CHECKSUM]      VARBINARY(64) NOT NULL,
  [EXECUTED_CODE] NVARCHAR(MAX) NOT NULL,

  CONSTRAINT [PK_OMD_MODULE_INSTANCE_EXECUTED_CODE]
    PRIMARY KEY CLUSTERED ([CHECKSUM] ASC)
);
