CREATE TABLE [omd].[BATCH_INSTANCE] (
  [BATCH_INSTANCE_ID]         BIGINT IDENTITY (1, 1)  NOT NULL,
  [BATCH_ID]                  INT                     NOT NULL,
  [PARENT_BATCH_INSTANCE_ID]  BIGINT                  NOT NULL,
  [START_TIMESTAMP]           DATETIME2               NOT NULL,
  [END_TIMESTAMP]             DATETIME2               NULL,
  [INTERNAL_PROCESSING_CODE]  NVARCHAR (100)          NOT NULL,
  [NEXT_RUN_STATUS_CODE]      NVARCHAR (100)          NOT NULL,
  [EXECUTION_STATUS_CODE]     NVARCHAR (100)          NOT NULL,
  [EXECUTION_CONTEXT]         NVARCHAR (4000)         NULL,

  CONSTRAINT [PK_OMD_BATCH_INSTANCE]
    PRIMARY KEY CLUSTERED ([BATCH_INSTANCE_ID] ASC),

  CONSTRAINT [FK_OMD_BATCH_INSTANCE_OMD_BATCH]
    FOREIGN KEY ([BATCH_ID])
    REFERENCES [omd].[BATCH] ([BATCH_ID]),

  CONSTRAINT [FK_OMD_BATCH_INSTANCE_OMD_BATCH_INSTANCE]
    FOREIGN KEY ([PARENT_BATCH_INSTANCE_ID])
    REFERENCES [omd].[BATCH_INSTANCE] ([BATCH_INSTANCE_ID]),

  CONSTRAINT [FK_OMD_BATCH_INSTANCE_OMD_METADATA_EXECUTION_STATUS]
    FOREIGN KEY ([EXECUTION_STATUS_CODE])
    REFERENCES [omd_metadata].[EXECUTION_STATUS] ([EXECUTION_STATUS_CODE]),

  CONSTRAINT [FK_OMD_BATCH_INSTANCE_OMD_METADATA_NEXT_RUN_STATUS]
    FOREIGN KEY ([NEXT_RUN_STATUS_CODE])
    REFERENCES [omd_metadata].[NEXT_RUN_STATUS] ([NEXT_RUN_STATUS_CODE]),

  CONSTRAINT [FK_OMD_BATCH_INSTANCE_OMD_METADATA_INTERNAL_PROCESSING_STATUS]
    FOREIGN KEY ([INTERNAL_PROCESSING_CODE])
    REFERENCES [omd_metadata].[INTERNAL_PROCESSING_STATUS] ([INTERNAL_PROCESSING_STATUS_CODE])
);
