CREATE TABLE [omd].[BATCH_HIERARCHY] (
  [PARENT_BATCH_ID]   INT                     NOT NULL,
  [BATCH_ID]          INT                     NOT NULL,
  [SEQUENCE]          INT
    CONSTRAINT [DF_OMD_BATCH_HIERARCHY_SEQUENCE]
    DEFAULT (0)                               NOT NULL,
  [ACTIVE_INDICATOR]    CHAR (1)
    CONSTRAINT [DF_OMD_BATCH_HIERARCHY_ACTIVE_INDICATOR]
    DEFAULT ('Y')                             NOT NULL,

  CONSTRAINT [PK_OMD_BATCH_HIERARCHY]
    PRIMARY KEY CLUSTERED ([PARENT_BATCH_ID] ASC, [BATCH_ID] ASC),

  CONSTRAINT [FK_OMD_BATCH_HIERARCHY_OMD_BATCH]
    FOREIGN KEY ([BATCH_ID])
    REFERENCES [omd].[BATCH] ([BATCH_ID]),

  CONSTRAINT [FK_OMD_BATCH_HIERARCHY_OMD_BATCH_PARENT_BATCH]
    FOREIGN KEY ([PARENT_BATCH_ID])
    REFERENCES [omd].[BATCH] ([BATCH_ID]),
);
