CREATE TABLE [omd].[MODULE_PARAMETER] (
  [MODULE_ID]         INT                                   NOT NULL,
  [PARAMETER_ID]      INT                                   NOT NULL,
  [ACTIVE_INDICATOR]  CHAR (1)
    CONSTRAINT [DF_OMD_MODULE_PARAMETER_ACTIVE_INDICATOR]
    DEFAULT ('Y')                                           NOT NULL,

  CONSTRAINT [PK_OMD_MODULE_PARAMETER]
    PRIMARY KEY CLUSTERED ([MODULE_ID] ASC, [PARAMETER_ID] ASC),

  CONSTRAINT [FK_OMD_MODULE_PARAMETER_OMD_MODULE]
    FOREIGN KEY ([MODULE_ID])
    REFERENCES [omd].[MODULE] ([MODULE_ID]),

  CONSTRAINT [FK_OMD_MODULE_PARAMETER_OMD_PARAMETER]
    FOREIGN KEY ([PARAMETER_ID])
    REFERENCES [omd].[PARAMETER] ([PARAMETER_ID])
);
