CREATE TABLE [omd].[PARAMETER] (
  [PARAMETER_ID]          INT IDENTITY (1, 1)       NOT NULL,
  [PARAMETER_KEY_CODE]    NVARCHAR (1000)           NOT NULL,
  [PARAMETER_VALUE_CODE]  NVARCHAR (4000)           NOT NULL,
  [ACTIVE_INDICATOR]      CHAR (1)
    CONSTRAINT [DF_OMD_PARAMETER_ACTIVE_INDICATOR]
    DEFAULT ('Y')                                   NOT NULL,
  [PARAMETER_DESCRIPTION] NVARCHAR (4000)           NOT NULL,

  CONSTRAINT [PK_OMD_PARAMETER]
    PRIMARY KEY CLUSTERED ([PARAMETER_ID] ASC)
);
