CREATE TABLE [omd].[MODULE_INSTANCE] (
  [MODULE_INSTANCE_ID]        BIGINT IDENTITY (1, 1)  NOT NULL,
  [MODULE_ID]                 INT                     NOT NULL,
  [BATCH_INSTANCE_ID]         BIGINT                  NOT NULL,
  [START_TIMESTAMP]           DATETIME2               NOT NULL,
  [END_TIMESTAMP]             DATETIME2               NULL,
  [INTERNAL_PROCESSING_CODE]  NVARCHAR (100)          NOT NULL,
  [NEXT_RUN_STATUS_CODE]      NVARCHAR (100)          NOT NULL,
  [EXECUTION_STATUS_CODE]     NVARCHAR (100)          NOT NULL,
  [EXECUTION_CONTEXT]         NVARCHAR (4000)         NULL,
  [ROWS_INPUT]                INT                     NULL,
  [ROWS_INSERTED]             INT                     NULL,
  [ROWS_UPDATED]              INT                     NULL,
  [ROWS_DELETED]              INT                     NULL,
  [ROWS_DISCARDED]            INT                     NULL,
  [ROWS_REJECTED]             INT                     NULL,
  [EXECUTED_CODE_CHECKSUM]    VARBINARY(64)           NULL,

  CONSTRAINT [PK_MODULE_INSTANCE]
    PRIMARY KEY CLUSTERED ([MODULE_INSTANCE_ID] ASC),

  CONSTRAINT [FK_OMD_MODULE_INSTANCE_OMD_BATCH_INSTANCE]
    FOREIGN KEY ([BATCH_INSTANCE_ID])
    REFERENCES [omd].[BATCH_INSTANCE] ([BATCH_INSTANCE_ID]),

  CONSTRAINT [FK_OMD_MODULE_INSTANCE_OMD_METADATA_EXECUTION_STATUS_CODE]
    FOREIGN KEY ([EXECUTION_STATUS_CODE])
    REFERENCES [omd_metadata].[EXECUTION_STATUS] ([EXECUTION_STATUS_CODE]),

  CONSTRAINT [FK_OMD_MODULE_INSTANCE_OMD_MODULE]
    FOREIGN KEY ([MODULE_ID])
    REFERENCES [omd].[MODULE] ([MODULE_ID]),

  CONSTRAINT [FK_OMD_MODULE_INSTANCE_OMD_METADATA_NEXT_RUN_STATUS]
    FOREIGN KEY ([NEXT_RUN_STATUS_CODE])
    REFERENCES [omd_metadata].[NEXT_RUN_STATUS] ([NEXT_RUN_STATUS_CODE]),

  CONSTRAINT [FK_OMD_MODULE_INSTANCE_OMD_METADATA_PROCESSING_STATUS]
    FOREIGN KEY ([INTERNAL_PROCESSING_CODE])
    REFERENCES [omd_metadata].[INTERNAL_PROCESSING_STATUS] ([INTERNAL_PROCESSING_STATUS_CODE])
);

GO

CREATE INDEX IX_OMD_MODULE_INSTANCE_OMD_BATCH_INSTANCE_ID
  ON [omd].[MODULE_INSTANCE] ([BATCH_INSTANCE_ID]);
