CREATE TABLE [omd].[BATCH] (
  [BATCH_ID]            INT IDENTITY (1, 1)         NOT NULL,
  [BATCH_CODE]          NVARCHAR (1000)             NOT NULL,
  [BATCH_TYPE]          NVARCHAR (100)              NULL,
  [FREQUENCY_CODE]      NVARCHAR (100)
    CONSTRAINT [DF_OMD_BATCH_FREQUENCY_CODE]
    DEFAULT (N'On-demand')                          NOT NULL,
  [ACTIVE_INDICATOR]    CHAR (1)
    CONSTRAINT [DF_OMD_BATCH_ACTIVE_INDICATOR]
    DEFAULT ('Y')                                   NOT NULL,
  [BATCH_DESCRIPTION]   NVARCHAR (4000)             NULL,

  CONSTRAINT [PK_OMD_BATCH]
    PRIMARY KEY CLUSTERED ([BATCH_ID] ASC),

  CONSTRAINT [IX_OMD_BATCH]
    UNIQUE NONCLUSTERED ([BATCH_CODE] ASC)
);
