CREATE TABLE [omd].[BATCH_MODULE] (
  [BATCH_ID]          INT                     NOT NULL,
  [MODULE_ID]         INT                     NOT NULL,
  [SEQUENCE]          INT
    CONSTRAINT [DF_OMD_BATCH_MODULE_SEQUENCE]
    DEFAULT (0)                               NOT NULL,
  [ACTIVE_INDICATOR]  CHAR (1)
    CONSTRAINT [DF_OMD_BATCH_MODULE_ACTIVE_INDICATOR]
    DEFAULT ('Y')                             NOT NULL,

  CONSTRAINT [PK_OMD_BATCH_MODULE]
    PRIMARY KEY CLUSTERED ([BATCH_ID] ASC, [MODULE_ID] ASC),

  CONSTRAINT [FK_OMD_BATCH_MODULE_OMD_BATCH]
    FOREIGN KEY ([BATCH_ID])
    REFERENCES [omd].[BATCH] ([BATCH_ID]),

  CONSTRAINT [FK_OMD_BATCH_MODULE_OMD_MODULE]
    FOREIGN KEY ([MODULE_ID])
    REFERENCES [omd].[MODULE] ([MODULE_ID])
);
