CREATE TABLE [omd].[BATCH_PARAMETER] (
  [BATCH_ID]          INT                     NOT NULL,
  [PARAMETER_ID]      INT                     NOT NULL,
  [ACTIVE_INDICATOR]  CHAR (1)
    CONSTRAINT [DF_OMD_BATCH_PARAMETER_ACTIVE_INDICATOR]
    DEFAULT ('Y')                             NOT NULL,

  CONSTRAINT [PK_OMD_BATCH_PARAMETER]
    PRIMARY KEY CLUSTERED ([BATCH_ID] ASC, [PARAMETER_ID] ASC),

  CONSTRAINT [FK_OMD_BATCH_PARAMETER_OMD_BATCH]
    FOREIGN KEY ([BATCH_ID])
    REFERENCES [omd].[BATCH] ([BATCH_ID]),

  CONSTRAINT [FK_OMD_BATCH_PARAMETER_OMD_PARAMETER]
    FOREIGN KEY ([PARAMETER_ID])
    REFERENCES [omd].[PARAMETER] ([PARAMETER_ID])
);
