CREATE TABLE [omd].[SOURCE_CONTROL] (
  [MODULE_SOURCE_CONTROL_ID]  BIGINT IDENTITY (1, 1)              NOT NULL,
  [MODULE_ID]                 INT                                 NOT NULL,
  [MODULE_INSTANCE_ID]        BIGINT                              NOT NULL,
  [INSERT_TIMESTAMP]          DATETIME2
    CONSTRAINT [DF_OMD_SOURCE_CONTROL_INSERT_TIMESTAMP]
    DEFAULT(SYSUTCDATETIME())                                     NULL,
  [START_VALUE]               DATETIME2                           NULL,
  [END_VALUE]                 DATETIME2                           NULL,

  CONSTRAINT [PK_OMD_SOURCE_CONTROL]
    PRIMARY KEY CLUSTERED ([MODULE_SOURCE_CONTROL_ID] ASC),

  CONSTRAINT [FK_OMD_SOURCE_CONTROL_OMD_MODULE_INSTANCE]
    FOREIGN KEY ([MODULE_INSTANCE_ID])
    REFERENCES [omd].[MODULE_INSTANCE] ([MODULE_INSTANCE_ID]),

  CONSTRAINT [FK_OMD_SOURCE_CONTROL_OMD_MODULE]
    FOREIGN KEY ([MODULE_ID])
    REFERENCES [omd].[MODULE] ([MODULE_ID]),
);
