CREATE TABLE [omd].[EVENT_LOG] (
  [EVENT_ID]                  BIGINT IDENTITY (1, 1)          NOT NULL,
  [BATCH_INSTANCE_ID]         BIGINT
    CONSTRAINT [DF_OMD_EVENT_LOG_BATCH_INSTANCE_ID]
    DEFAULT (0)                                               NOT NULL,
  [MODULE_INSTANCE_ID]        BIGINT
    CONSTRAINT [DF_OMD_EVENT_LOG_MODULE_INSTANCE_ID]
    DEFAULT (0)                                               NOT NULL,
  [EVENT_TYPE_CODE]           NVARCHAR (100)                  NOT NULL,
  [EVENT_TIMESTAMP]           DATETIME2
    CONSTRAINT [DF_OMD_EVENT_LOG_EVENT_TIMESTAMP]
    DEFAULT (SYSUTCDATETIME())                                NOT NULL,
  [EVENT_RETURN_CODE]         NVARCHAR (100)                  NULL,
  [EVENT_DETAIL]              NVARCHAR (4000)                 NOT NULL,
  [ERROR_BITMAP]              NUMERIC (20)                    NULL,

  CONSTRAINT [PK_OMD_EVENT_LOG]
    PRIMARY KEY CLUSTERED ([EVENT_ID] ASC),

  CONSTRAINT [FK_OMD_EVENT_LOG_OMD_BATCH_INSTANCE]
    FOREIGN KEY ([BATCH_INSTANCE_ID])
    REFERENCES [omd].[BATCH_INSTANCE] ([BATCH_INSTANCE_ID]),

  CONSTRAINT [FK_OMD_EVENT_LOG_OMD_METADATA_EVENT_TYPE]
    FOREIGN KEY ([EVENT_TYPE_CODE])
    REFERENCES [omd_metadata].[EVENT_TYPE] ([EVENT_TYPE_CODE]),

  CONSTRAINT [FK_OMD_EVENT_LOG_OMD_MODULE_INSTANCE]
    FOREIGN KEY ([MODULE_INSTANCE_ID])
    REFERENCES [omd].[MODULE_INSTANCE] ([MODULE_INSTANCE_ID])
);
