CREATE TABLE [omd_metadata].[NEXT_RUN_STATUS] (
  [NEXT_RUN_STATUS_CODE]  NVARCHAR (100)   NOT NULL,
  [NEXT_RUN_STATUS_DESCRIPTION]  NVARCHAR (4000)  NULL,

  CONSTRAINT [PK_OMD_METADATA_NEXT_RUN_STATUS]
    PRIMARY KEY CLUSTERED ([NEXT_RUN_STATUS_CODE] ASC)
);
