CREATE TABLE [omd_metadata].[EVENT_TYPE] (
  [EVENT_TYPE_CODE]             NVARCHAR (100)  NOT NULL,
  [EVENT_TYPE_CODE_DESCRIPTION] NVARCHAR (4000) NULL,

  CONSTRAINT [PK_OMD_METADATA_EVENT_TYPE]
    PRIMARY KEY CLUSTERED ([EVENT_TYPE_CODE] ASC)
);
