CREATE TABLE [omd_metadata].[EXECUTION_STATUS] (
  [EXECUTION_STATUS_CODE]        NVARCHAR (100)   NOT NULL,
  [EXECUTION_STATUS_DESCRIPTION] NVARCHAR (4000)  NULL,

  CONSTRAINT [PK_OMD_METADATA_EXECUTION_STATUS]
    PRIMARY KEY CLUSTERED ([EXECUTION_STATUS_CODE] ASC)
);
