CREATE VIEW [omd_reporting].[vw_EXECUTION_LOG_BATCH_INSTANCE]
AS

SELECT	
	  BI.BATCH_INSTANCE_ID
	, B.BATCH_CODE
	, BI.BATCH_EXECUTION_SYSTEM_ID
	, BI.START_DATETIME
	, BI.END_DATETIME
	, CAST (CAST ((BI.END_DATETIME - BI.START_DATETIME) AS TIME) AS VARCHAR (30)) AS EXECUTION_TIME
	, PIND.PROCESSING_INDICATOR_DESCRIPTION
	, NR.NEXT_RUN_INDICATOR_DESCRIPTION
	, BI.EXECUTION_STATUS_CODE
	, ES.EXECUTION_STATUS_DESCRIPTION 
FROM
	       omd.BATCH_INSTANCE BI
INNER JOIN omd.BATCH B ON BI.BATCH_ID = B.BATCH_ID
INNER JOIN omd.PROCESSING_INDICATOR PIND ON BI.PROCESSING_INDICATOR = PIND.PROCESSING_INDICATOR
INNER JOIN omd.NEXT_RUN_INDICATOR NR ON BI.NEXT_RUN_INDICATOR = NR.NEXT_RUN_INDICATOR
INNER JOIN omd.EXECUTION_STATUS ES ON BI.EXECUTION_STATUS_CODE = ES.EXECUTION_STATUS_CODE
WHERE
	BATCH_INSTANCE_ID <> 0


