/* Created separately due to reliance on SSISDB */

CREATE VIEW [omd_processing].[vw_QUEUE_MODULE_PROCESSING]
AS

SELECT MODULE_ID, 
	ETL_PROCESS_NAME, 
	END_DATETIME,
	ROW_NUMBER() OVER( ORDER BY END_DATETIME) QUEUE_ORDER
FROM (
	SELECT 
		   MODULE.MODULE_ID, 
		   MODULE.MODULE_CODE,
		   MODULE.MODULE_CODE+'.dtsx' AS ETL_PROCESS_NAME, 
		   COALESCE(END_DATETIME,'1900-01-01') AS END_DATETIME,
		   COALESCE(EXECUTION_STATUS_CODE,'S') AS EXECUTION_STATUS_CODE,
		   ROW_NUMBER() OVER(PARTITION BY MODULE.DATA_OBJECT_TARGET ORDER BY CASE COALESCE(EXECUTION_STATUS_CODE,'S') WHEN 'E' THEN 1 ELSE 2 END, END_DATETIME) BY_DATA_STORE
	FROM omd.MODULE MODULE
		LEFT JOIN omd.MODULE_INSTANCE main
				ON main.MODULE_ID=MODULE.MODULE_ID
		LEFT JOIN (
				SELECT MODULE.MODULE_ID, COALESCE(MAX(MODULE_INSTANCE_ID),0) MOST_RECENT_EXECUTION_MODULE_ID 
				FROM omd.MODULE MODULE
					LEFT JOIN omd.MODULE_INSTANCE MODULE_instance
							ON MODULE.MODULE_ID=MODULE_instance.MODULE_ID
				WHERE MODULE.MODULE_ID<>0
				GROUP BY MODULE.MODULE_ID
				) most_recent
				ON MODULE.MODULE_ID = most_recent.MODULE_ID AND COALESCE(main.MODULE_INSTANCE_ID,0) = most_recent.MOST_RECENT_EXECUTION_MODULE_ID 
	WHERE MODULE.INACTIVE_INDICATOR = 'N'
		AND MODULE.AREA_CODE = 'INT'
		AND MODULE.FREQUENCY_CODE = 'Queue'
		AND MODULE.MODULE_ID <> 0
		AND (MOST_RECENT_EXECUTION_MODULE_ID IS NOT NULL OR MOST_RECENT_EXECUTION_MODULE_ID=0)
	) as sq
WHERE BY_DATA_STORE = 1
	AND EXECUTION_STATUS_CODE != 'E'
	AND NOT EXISTS (SELECT package_name FROM [$(SSISDB)].[catalog].executions jobs WHERE end_time IS NULL and jobs.package_name = MODULE_CODE + '.dtsx' COLLATE DATABASE_DEFAULT)