CREATE VIEW [omd_reporting].[vw_EXCEPTIONS_NON_RUNNING_BATCHES] AS
SELECT
    BATCH.BATCH_CODE,
    BATCH.BATCH_ID,
    BATCH.BATCH_DESCRIPTION,
    main.BATCH_INSTANCE_ID AS MOST_RECENT_BATCH_INSTANCE_ID,
    main.START_DATETIME,
    main.END_DATETIME,
    main.EXECUTION_STATUS_CODE
FROM omd.BATCH_INSTANCE main
JOIN omd.BATCH BATCH ON main.BATCH_ID=BATCH.BATCH_ID
JOIN
    (
        SELECT BATCH_ID, MAX(BATCH_INSTANCE_ID) as MAX_BATCH_INSTANCE_ID
        FROM omd.BATCH_INSTANCE
        WHERE BATCH_ID>0
        GROUP BY BATCH_ID
    ) maxsub
ON main.BATCH_ID=maxsub.BATCH_ID
AND main.BATCH_INSTANCE_ID=maxsub.MAX_BATCH_INSTANCE_ID
WHERE DATEDIFF(dd,START_DATETIME, GETDATE())>=60
AND INACTIVE_INDICATOR='N'
