CREATE VIEW [omd_reporting].[vw_EXECUTION_LOG_MODULE_INSTANCE]
AS

SELECT
	  MI.MODULE_INSTANCE_ID
	, MI.MODULE_EXECUTION_SYSTEM_ID
	, MI.BATCH_INSTANCE_ID
	, M.MODULE_CODE
	, MI.START_DATETIME
	, MI.END_DATETIME
	, CAST (CAST ((MI.END_DATETIME - MI.START_DATETIME) AS TIME) AS VARCHAR (30)) AS EXECUTION_TIME
	, PIND.PROCESSING_INDICATOR_DESCRIPTION
	, NR.NEXT_RUN_INDICATOR_DESCRIPTION
	, MI.EXECUTION_STATUS_CODE
	, ES.EXECUTION_STATUS_DESCRIPTION
	, MI.ROWS_INPUT
	, MI.ROWS_INSERTED
	, MI.ROWS_UPDATED
	, MI.ROWS_DELETED
	, MI.ROWS_DISCARDED
	, MI.ROWS_REJECTED
FROM
	omd.MODULE_INSTANCE MI
		INNER JOIN omd.MODULE M ON MI.MODULE_ID = M.MODULE_ID
		INNER JOIN omd.PROCESSING_INDICATOR PIND ON MI.PROCESSING_INDICATOR = PIND.PROCESSING_INDICATOR
		INNER JOIN omd.NEXT_RUN_INDICATOR NR ON MI.NEXT_RUN_INDICATOR = NR.NEXT_RUN_INDICATOR
		INNER JOIN omd.EXECUTION_STATUS ES ON MI.EXECUTION_STATUS_CODE = ES.EXECUTION_STATUS_CODE
WHERE MODULE_INSTANCE_ID <> 0

