CREATE VIEW omd_reporting.vw_EXCEPTIONS_BATCH AS 

SELECT
    batch.BATCH_CODE,
    main.EXECUTION_STATUS_CODE,
    main.BATCH_INSTANCE_ID AS MOST_RECENT_BATCH_INSTANCE_ID,
    main.START_DATETIME,
    main.END_DATETIME
FROM omd.BATCH_INSTANCE main
JOIN omd.BATCH batch ON main.BATCH_ID=batch.BATCH_ID
JOIN
    (
        SELECT BATCH_ID, MAX(BATCH_INSTANCE_ID) as MAX_BATCH_INSTANCE_ID
        FROM omd.BATCH_INSTANCE
        WHERE BATCH_ID>0
        GROUP BY BATCH_ID
    ) maxsub
ON  main.BATCH_ID = maxsub.BATCH_ID
AND main.BATCH_INSTANCE_ID=maxsub.MAX_BATCH_INSTANCE_ID
WHERE main.EXECUTION_STATUS_CODE<>'S' AND batch.INACTIVE_INDICATOR='N'

