CREATE TABLE [omd].[PARAMETER] (
    [PARAMETER_ID]          INT IDENTITY (1, 1) NOT NULL,
    [PARAMETER_DESCRIPTION] VARCHAR (1000) NOT NULL,
    [PARAMETER_KEY_CODE]    VARCHAR (100)  NOT NULL,
    [PARAMETER_VALUE_CODE]  VARCHAR (100)  NOT NULL,
    [INACTIVE_INDICATOR]    VARCHAR (1) DEFAULT ('N') NOT NULL,
    CONSTRAINT PK_PARAMETER PRIMARY KEY CLUSTERED ([PARAMETER_ID] ASC)
);