CREATE TABLE [omd].[MODULE_PARAMETER] (
    [MODULE_ID]    INT NOT NULL,
    [PARAMETER_ID] INT NOT NULL,
    [INACTIVE_INDICATOR] VARCHAR (1)    DEFAULT ('N') NOT NULL,
    CONSTRAINT PK_MODULE_PARAMETER PRIMARY KEY CLUSTERED ([MODULE_ID] ASC, [PARAMETER_ID] ASC),
    CONSTRAINT FK_MODULE_PARAMETER FOREIGN KEY ([MODULE_ID]) REFERENCES [omd].[MODULE] ([MODULE_ID]),
    CONSTRAINT FK_MODULE_MODULE_PARAMETER FOREIGN KEY ([PARAMETER_ID]) REFERENCES [omd].[PARAMETER] ([PARAMETER_ID])
);

