CREATE TABLE [omd].[BATCH_INSTANCE] (
    [BATCH_INSTANCE_ID]         INT           IDENTITY (1, 1) NOT NULL,
    [BATCH_ID]                  INT           NOT NULL,
    [START_DATETIME]            DATETIME      NOT NULL,
    [END_DATETIME]              DATETIME      NULL,
    [PROCESSING_INDICATOR]      VARCHAR (1)   NULL,
    [NEXT_RUN_INDICATOR]        VARCHAR (1)   NULL,
    [EXECUTION_STATUS_CODE]     VARCHAR (1)   NULL,
    [BATCH_EXECUTION_SYSTEM_ID] VARCHAR (100) NULL,
    CONSTRAINT PK_BATCH_INSTANCE PRIMARY KEY CLUSTERED ([BATCH_INSTANCE_ID] ASC),
    CONSTRAINT FK_BATCH_INSTANCE_BATCH FOREIGN KEY ([BATCH_ID]) REFERENCES [omd].[BATCH] ([BATCH_ID]),
    CONSTRAINT FK_BATCH_INSTANCE_EXECUTION_STATUS FOREIGN KEY ([EXECUTION_STATUS_CODE])  REFERENCES [omd].[EXECUTION_STATUS] ([EXECUTION_STATUS_CODE]),
    CONSTRAINT FK_BATCH_INSTANCE_NEXT_RUN_INDICATOR FOREIGN KEY ([NEXT_RUN_INDICATOR]) REFERENCES [omd].[NEXT_RUN_INDICATOR] ([NEXT_RUN_INDICATOR]),
    CONSTRAINT FK_BATCH_INSTANCE_PROCESSING_INDICATOR FOREIGN KEY ([PROCESSING_INDICATOR]) REFERENCES [omd].[PROCESSING_INDICATOR] ([PROCESSING_INDICATOR])
);

