CREATE TABLE omd.[EVENT_LOG] (
    [EVENT_ID]                  INT            IDENTITY (1, 1) NOT NULL,
    [BATCH_INSTANCE_ID]         INT            NOT NULL,
    [MODULE_INSTANCE_ID]        INT            NOT NULL,
    [EVENT_TYPE_CODE]           VARCHAR (100)  NOT NULL,
    [EVENT_DATETIME]            DATETIME       NOT NULL,
    [EVENT_RETURN_CODE_DETAILS] VARCHAR (1000) NOT NULL,
    [EVENT_DETAIL]              VARCHAR (4000) NOT NULL,
    [ERROR_BITMAP]              NUMERIC (20)   NULL,
    CONSTRAINT PK_EVENT_LOG PRIMARY KEY CLUSTERED ([EVENT_ID] ASC),
    CONSTRAINT FK_BATCH_EVENT FOREIGN KEY ([BATCH_INSTANCE_ID]) REFERENCES [omd].[BATCH_INSTANCE] ([BATCH_INSTANCE_ID]),
    CONSTRAINT FK_EVENT_LOG_EVENT_TYPE FOREIGN KEY ([EVENT_TYPE_CODE]) REFERENCES [omd].[EVENT_TYPE] ([EVENT_TYPE_CODE]),
    CONSTRAINT FK_MODULE_INSTANCE_EVENT_LOG FOREIGN KEY ([MODULE_INSTANCE_ID]) REFERENCES [omd].[MODULE_INSTANCE] ([MODULE_INSTANCE_ID])
);

