CREATE TABLE [omd].[NEXT_RUN_INDICATOR] (
    [NEXT_RUN_INDICATOR]             VARCHAR (1)   NOT NULL,
    [NEXT_RUN_INDICATOR_DESCRIPTION] VARCHAR (100) NOT NULL,
    CONSTRAINT PK_NEXT_RUN_INDICATOR PRIMARY KEY CLUSTERED ([NEXT_RUN_INDICATOR] ASC)
);

