CREATE TABLE [omd].[BATCH_MODULE] (
    [BATCH_ID]           INT         NOT NULL,
    [MODULE_ID]          INT         NOT NULL,
    [INACTIVE_INDICATOR] VARCHAR (1) DEFAULT ('N') NOT NULL,
    CONSTRAINT PK_BATCH_MODULE PRIMARY KEY CLUSTERED ([BATCH_ID] ASC, [MODULE_ID] ASC),
    CONSTRAINT FK_BATCH_MODULE_BATCH FOREIGN KEY ([BATCH_ID]) REFERENCES [omd].[BATCH] ([BATCH_ID]),
    CONSTRAINT FK_BATCH_MODULE_MODULE FOREIGN KEY ([MODULE_ID]) REFERENCES [omd].[MODULE] ([MODULE_ID])
);

