CREATE TABLE [omd].[SOURCE_CONTROL] (
    [MODULE_SOURCE_CONTROL_ID]  INT           IDENTITY (1, 1) NOT NULL,
    [MODULE_INSTANCE_ID]        INT           NOT NULL,
    [INSERT_DATETIME]           DATETIME2 (7) NULL,
    [INTERVAL_DATETIME]         DATETIME2 (7) NULL,
    [INTERVAL_START_DATETIME]   DATETIME2 (7) NULL,
    [INTERVAL_END_DATETIME]     DATETIME2 (7) NULL,
    [INTERVAL_START_IDENTIFIER] BIGINT        NULL,
    [INTERVAL_END_IDENTIFIER]   BIGINT        NULL,
    CONSTRAINT PK_SOURCE_CONTROL PRIMARY KEY CLUSTERED ([MODULE_SOURCE_CONTROL_ID] ASC),
    CONSTRAINT FK_MODULE_INSTANCE_SOURCE_CONTROL FOREIGN KEY ([MODULE_INSTANCE_ID]) REFERENCES [omd].[MODULE_INSTANCE] ([MODULE_INSTANCE_ID])
);

