CREATE TABLE [omd].[AREA] (
    [AREA_CODE]        VARCHAR (100)  NOT NULL,
    [LAYER_CODE]       VARCHAR (100)  NOT NULL,
    [AREA_DESCRIPTION] VARCHAR (1000) NOT NULL,
    CONSTRAINT PK_AREA PRIMARY KEY CLUSTERED ([AREA_CODE] ASC),
    CONSTRAINT FK_AREA_LAYER FOREIGN KEY ([LAYER_CODE]) REFERENCES [omd].[LAYER] ([LAYER_CODE])
);

