CREATE TABLE [omd].[EXECUTION_STATUS] (
    [EXECUTION_STATUS_CODE]        VARCHAR (1)  NOT NULL,
    [EXECUTION_STATUS_DESCRIPTION] VARCHAR (1000) NOT NULL,
    CONSTRAINT PK_EXECUTION_STATUS PRIMARY KEY CLUSTERED ([EXECUTION_STATUS_CODE] ASC)
);

