CREATE TABLE [omd].[MODULE_INSTANCE] (
    [MODULE_INSTANCE_ID]         INT           IDENTITY (1, 1) NOT NULL,
    [MODULE_ID]                  INT           NOT NULL,
    [BATCH_INSTANCE_ID]          INT           NOT NULL,
    [START_DATETIME]             DATETIME      NOT NULL,
    [END_DATETIME]               DATETIME      NULL,
    [PROCESSING_INDICATOR]       VARCHAR (1)   NOT NULL,
    [NEXT_RUN_INDICATOR]         VARCHAR (1)   NOT NULL,
    [EXECUTION_STATUS_CODE]      VARCHAR (1)   NOT NULL,
    [MODULE_EXECUTION_SYSTEM_ID] VARCHAR (100) NULL,
    [ROWS_INPUT]                 INT           NULL,
    [ROWS_INSERTED]              INT           NULL,
    [ROWS_UPDATED]               INT           NULL,
    [ROWS_DELETED]               INT           NULL,
    [ROWS_DISCARDED]             INT           NULL,
    [ROWS_REJECTED]              INT           NULL,
    CONSTRAINT PK_MODULE_INSTANCE PRIMARY KEY CLUSTERED ([MODULE_INSTANCE_ID] ASC),
    CONSTRAINT FK_MODULE_INSTANCE_BATCH_INSTANCE FOREIGN KEY ([BATCH_INSTANCE_ID]) REFERENCES [omd].[BATCH_INSTANCE] ([BATCH_INSTANCE_ID]),
    CONSTRAINT FK_MODULE_INSTANCE_EXECUTION_STATUS_CODE FOREIGN KEY ([EXECUTION_STATUS_CODE]) REFERENCES [omd].[EXECUTION_STATUS] ([EXECUTION_STATUS_CODE]),
    CONSTRAINT FK_MODULE_INSTANCE_MODULE FOREIGN KEY ([MODULE_ID]) REFERENCES [omd].[MODULE] ([MODULE_ID]),
    CONSTRAINT FK_MODULE_INSTANCE_NEXT_RUN_INDICATOR FOREIGN KEY ([NEXT_RUN_INDICATOR]) REFERENCES [omd].[NEXT_RUN_INDICATOR] ([NEXT_RUN_INDICATOR]),
    CONSTRAINT FK_MODULE_INSTANCE_PROCESSING_INDICATOR FOREIGN KEY ([PROCESSING_INDICATOR]) REFERENCES [omd].[PROCESSING_INDICATOR] ([PROCESSING_INDICATOR])
);

