CREATE TABLE [omd].[PROCESSING_INDICATOR] (
    [PROCESSING_INDICATOR]             VARCHAR (1)   NOT NULL,
    [PROCESSING_INDICATOR_DESCRIPTION] VARCHAR (100) NOT NULL,
    CONSTRAINT PK_PROCESSING_INDICATOR PRIMARY KEY CLUSTERED ([PROCESSING_INDICATOR] ASC)
);

