USE <DIRECT Database>

-- Exception check Batch level
SELECT
    batch.BATCH_CODE,
    main.BATCH_INSTANCE_ID AS MOST_RECENT_BATCH_INSTANCE_ID,
    main.START_DATETIME,
    main.END_DATETIME,
    main.EXECUTION_STATUS_CODE
FROM BATCH_INSTANCE main
JOIN BATCH batch ON main.BATCH_ID=batch.BATCH_ID
JOIN
    (
        SELECT BATCH_ID, MAX(BATCH_INSTANCE_ID) as MAX_BATCH_INSTANCE_ID
        FROM BATCH_INSTANCE
        WHERE BATCH_ID>0
        GROUP BY BATCH_ID
    ) maxsub
ON main.BATCH_ID=maxsub.BATCH_ID
AND main.BATCH_INSTANCE_ID=maxsub.MAX_BATCH_INSTANCE_ID
WHERE main.EXECUTION_STATUS_CODE<>'S' AND batch.INACTIVE_INDICATOR='N'
ORDER BY 3 DESC

-- Exception check Module level
SELECT
    module.MODULE_CODE,
	main.BATCH_INSTANCE_ID,
    main.MODULE_INSTANCE_ID AS MOST_RECENT_MODULE_INSTANCE_ID,
    main.START_DATETIME,
    main.END_DATETIME,
    main.EXECUTION_STATUS_CODE
FROM MODULE_INSTANCE main
JOIN MODULE module ON main.MODULE_ID=module.MODULE_ID
JOIN
    (
        SELECT MODULE_ID, MAX(MODULE_INSTANCE_ID) as MAX_MODULE_INSTANCE_ID
        FROM MODULE_INSTANCE
        WHERE MODULE_ID>0
        GROUP BY MODULE_ID
    ) maxsub
ON main.MODULE_ID=maxsub.MODULE_ID
AND main.MODULE_INSTANCE_ID=maxsub.MAX_MODULE_INSTANCE_ID
WHERE main.EXECUTION_STATUS_CODE<>'S' AND module.INACTIVE_INDICATOR='N'
ORDER BY 3 DESC