DECLARE @ETL_PROCESS NVARCHAR(100);
DECLARE @SQL_STATEMENT NVARCHAR(MAX);

SET @ETL_PROCESS = ''

PRINT 'Working on '+@ETL_PROCESS+CHAR(13);
/* Event log Module errors*/
SET @SQL_STATEMENT = 'DELETE FROM EVENT_LOG WHERE MODULE_INSTANCE_ID IN (SELECT MODULE_INSTANCE_ID FROM MODULE_INSTANCE WHERE BATCH_INSTANCE_ID IN (SELECT BATCH_INSTANCE_ID FROM BATCH_INSTANCE WHERE BATCH_ID = (SELECT BATCH_ID FROM BATCH WHERE BATCH_CODE ='''+@ETL_PROCESS+''')))';
PRINT @SQL_STATEMENT;
EXEC sp_executesql @SQL_STATEMENT

/* Event log Batch errors*/
SET @SQL_STATEMENT = 'DELETE FROM EVENT_LOG WHERE BATCH_INSTANCE_ID IN (SELECT BATCH_INSTANCE_ID FROM BATCH_INSTANCE WHERE BATCH_ID = (SELECT BATCH_ID FROM BATCH WHERE BATCH_CODE ='''+@ETL_PROCESS+'''))';
PRINT @SQL_STATEMENT;
EXEC sp_executesql @SQL_STATEMENT

/* Source Control for some Modules */
SET @SQL_STATEMENT = 'DELETE FROM SOURCE_CONTROL WHERE MODULE_INSTANCE_ID IN (SELECT MODULE_INSTANCE_ID FROM MODULE_INSTANCE WHERE BATCH_INSTANCE_ID IN (SELECT BATCH_INSTANCE_ID FROM BATCH_INSTANCE WHERE BATCH_ID = (SELECT BATCH_ID FROM BATCH WHERE BATCH_CODE='''+@ETL_PROCESS+''')))';
PRINT @SQL_STATEMENT;
EXEC sp_executesql @SQL_STATEMENT

/* Module Instance */
SET @SQL_STATEMENT = 'DELETE FROM MODULE_INSTANCE WHERE BATCH_INSTANCE_ID IN (SELECT BATCH_INSTANCE_ID FROM BATCH_INSTANCE WHERE BATCH_ID = (SELECT BATCH_ID FROM BATCH WHERE BATCH_CODE ='''+@ETL_PROCESS+'''))';
PRINT @SQL_STATEMENT;
EXEC sp_executesql @SQL_STATEMENT

/* Batch Instance */
SET @SQL_STATEMENT = 'DELETE FROM BATCH_INSTANCE WHERE BATCH_ID = (SELECT BATCH_ID FROM BATCH WHERE BATCH_CODE ='''+@ETL_PROCESS+''')';
PRINT @SQL_STATEMENT;
EXEC sp_executesql @SQL_STATEMENT

/* Batch Module */
SET @SQL_STATEMENT = 'DELETE FROM BATCH_MODULE WHERE BATCH_ID = (SELECT BATCH_ID FROM BATCH WHERE BATCH_CODE ='''+@ETL_PROCESS+''')';
PRINT @SQL_STATEMENT;
EXEC sp_executesql @SQL_STATEMENT

/* Batch */
SET @SQL_STATEMENT = 'DELETE FROM BATCH WHERE BATCH_CODE ='''+@ETL_PROCESS+'''';
PRINT @SQL_STATEMENT;
EXEC sp_executesql @SQL_STATEMENT