--Show which modules haven't run in the last 3 days
SELECT 
	module.MODULE_CODE,
	module.MODULE_ID,
	main.MODULE_INSTANCE_ID AS MOST_RECENT_MODULE_INSTANCE_ID,
	main.START_DATETIME,
	main.END_DATETIME,
	main.EXECUTION_STATUS_CODE
FROM MODULE_INSTANCE main
JOIN MODULE module ON main.MODULE_ID=module.MODULE_ID
JOIN
	(
		SELECT MODULE_ID, MAX(MODULE_INSTANCE_ID) as MAX_MODULE_INSTANCE_ID
		FROM MODULE_INSTANCE
		WHERE MODULE_ID>0
		GROUP BY MODULE_ID
	) maxsub
ON main.MODULE_ID=maxsub.MODULE_ID
AND main.MODULE_INSTANCE_ID=maxsub.MAX_MODULE_INSTANCE_ID
WHERE DATEDIFF(dd,START_DATETIME, GETDATE())>=3
AND INACTIVE_INDICATOR='N'