DECLARE @ETL_PROCESS NVARCHAR(100);
DECLARE @SQL_STATEMENT NVARCHAR(MAX);


SET @ETL_PROCESS = ''

PRINT 'Working on '+@ETL_PROCESS+CHAR(13);
/* Source Control */
SET @SQL_STATEMENT = 'DELETE FROM SOURCE_CONTROL WHERE MODULE_INSTANCE_ID IN (SELECT MODULE_INSTANCE_ID FROM MODULE_INSTANCE WHERE MODULE_ID = (SELECT MODULE_ID FROM MODULE WHERE MODULE_CODE='''+@ETL_PROCESS+'''))'
PRINT @SQL_STATEMENT;
EXEC sp_executesql @SQL_STATEMENT

/* Event log */
SET @SQL_STATEMENT = 'DELETE FROM EVENT_LOG WHERE MODULE_INSTANCE_ID IN (SELECT MODULE_INSTANCE_ID FROM MODULE_INSTANCE WHERE MODULE_ID = (SELECT MODULE_ID FROM MODULE WHERE MODULE_CODE='''+@ETL_PROCESS+'''))'
PRINT @SQL_STATEMENT;
EXEC sp_executesql @SQL_STATEMENT

/* Module Instance */
SET @SQL_STATEMENT = 'DELETE FROM MODULE_INSTANCE WHERE MODULE_ID = (SELECT MODULE_ID FROM MODULE WHERE MODULE_CODE='''+@ETL_PROCESS+''')';
PRINT @SQL_STATEMENT;
EXEC sp_executesql @SQL_STATEMENT

/* Batch Module */
SET @SQL_STATEMENT = 'DELETE FROM BATCH_MODULE WHERE MODULE_ID = (SELECT MODULE_ID FROM MODULE WHERE MODULE_CODE='''+@ETL_PROCESS+''')';
PRINT @SQL_STATEMENT;
EXEC sp_executesql @SQL_STATEMENT

/* Module Data Store*/
SET @SQL_STATEMENT = 'DELETE FROM MODULE_DATA_STORE WHERE MODULE_ID = (SELECT MODULE_ID FROM MODULE WHERE MODULE_CODE='''+@ETL_PROCESS+''')';
PRINT @SQL_STATEMENT;
EXEC sp_executesql @SQL_STATEMENT

/* Module */
SET @SQL_STATEMENT = 'DELETE FROM MODULE WHERE MODULE_CODE='''+@ETL_PROCESS+'''';
PRINT @SQL_STATEMENT;
EXEC sp_executesql @SQL_STATEMENT

/* Batch Instance */
SET @SQL_STATEMENT = 'DELETE FROM BATCH_INSTANCE WHERE BATCH_ID = (SELECT BATCH_ID FROM BATCH WHERE BATCH_CODE ='''+@ETL_PROCESS+''')';
PRINT @SQL_STATEMENT;
EXEC sp_executesql @SQL_STATEMENT

/* Batch */
SET @SQL_STATEMENT = 'DELETE FROM BATCH WHERE BATCH_CODE ='''+@ETL_PROCESS+'''';
PRINT @SQL_STATEMENT;
EXEC sp_executesql @SQL_STATEMENT