/*
  DIRECT model revision 12
  Generated from SQL DBM (www.sqldbm.com)
  https://app.sqldbm.com/SQLServer/Share/wkTlhWhD3t1CbEDjp4xLEkGFrngIE8md_DYjF4jNYw0
*/

-- ****************** SqlDBM: Microsoft SQL Server ******************
-- ******************************************************************

DROP TABLE [dbo].[SOURCE_CONTROL];
GO


DROP TABLE [dbo].[EVENT_LOG];
GO


DROP TABLE [dbo].[MODULE_PARAMETER];
GO


DROP TABLE [dbo].[MODULE_INSTANCE];
GO


DROP TABLE [dbo].[MODULE_DATA_STORE];
GO


DROP TABLE [dbo].[BATCH_MODULE];
GO


DROP TABLE [dbo].[MODULE];
GO


DROP TABLE [dbo].[DATA_AUDIT];
GO


DROP TABLE [dbo].[BATCH_INSTANCE];
GO


DROP TABLE [dbo].[ERROR_BITMAP];
GO


DROP TABLE [dbo].[DATA_STORE];
GO


DROP TABLE [dbo].[BATCH];
GO


DROP TABLE [dbo].[AREA];
GO


DROP TABLE [dbo].[VERSION];
GO


DROP TABLE [dbo].[SEVERITY];
GO


DROP TABLE [dbo].[RECORD_SOURCE];
GO


DROP TABLE [dbo].[PROCESSING_INDICATOR];
GO


DROP TABLE [dbo].[PARAMETER];
GO


DROP TABLE [dbo].[NEXT_RUN_INDICATOR];
GO


DROP TABLE [dbo].[MODULE_TYPE];
GO


DROP TABLE [dbo].[LAYER];
GO


DROP TABLE [dbo].[FREQUENCY];
GO


DROP TABLE [dbo].[EXECUTION_STATUS];
GO


DROP TABLE [dbo].[EVENT_TYPE];
GO


DROP TABLE [dbo].[ERROR_TYPE];
GO


DROP TABLE [dbo].[DATA_STORE_TYPE];
GO


DROP TABLE [dbo].[DATA_AUDIT_TYPE];
GO


-- ************************************** [dbo].[VERSION]

CREATE TABLE [dbo].[VERSION]
(
 [VERSION_ID]   varchar(100) NOT NULL ,
 [COMMENTS]     varchar(4000) NOT NULL ,
 [RELEASE_DATE] datetime NOT NULL ,

 CONSTRAINT [PK_VERSION] PRIMARY KEY CLUSTERED ([VERSION_ID] ASC)
);
GO








-- ************************************** [dbo].[SEVERITY]

CREATE TABLE [dbo].[SEVERITY]
(
 [SEVERITY_CODE]        varchar(100) NOT NULL ,
 [SEVERITY_DESCRIPTION] varchar(1000) NOT NULL ,

 CONSTRAINT [PK_SEVERITY] PRIMARY KEY CLUSTERED ([SEVERITY_CODE] ASC)
);
GO








-- ************************************** [dbo].[RECORD_SOURCE]

CREATE TABLE [dbo].[RECORD_SOURCE]
(
 [RECORD_SOURCE_ID]   int IDENTITY (1, 1) NOT NULL ,
 [RECORD_SOURCE_CODE] varchar(20) NOT NULL ,

 CONSTRAINT [PK_RECORD_SOURCE] PRIMARY KEY CLUSTERED ([RECORD_SOURCE_ID] ASC)
);
GO








-- ************************************** [dbo].[PROCESSING_INDICATOR]

CREATE TABLE [dbo].[PROCESSING_INDICATOR]
(
 [PROCESSING_INDICATOR]             varchar(1) NOT NULL ,
 [PROCESSING_INDICATOR_DESCRIPTION] varchar(100) NOT NULL ,

 CONSTRAINT [PK_PROCESSING_INDICATOR] PRIMARY KEY CLUSTERED ([PROCESSING_INDICATOR] ASC)
);
GO








-- ************************************** [dbo].[PARAMETER]

CREATE TABLE [dbo].[PARAMETER]
(
 [PARAMETER_ID]          int IDENTITY (1, 1) NOT NULL ,
 [PARAMETER_DESCRIPTION] varchar(1000) NOT NULL ,
 [PARAMETER_KEY_CODE]    varchar(100) NOT NULL ,
 [PARAMETER_VALUE_CODE]  varchar(100) NOT NULL ,

 CONSTRAINT [PK_PARAMETER] PRIMARY KEY CLUSTERED ([PARAMETER_ID] ASC)
);
GO








-- ************************************** [dbo].[NEXT_RUN_INDICATOR]

CREATE TABLE [dbo].[NEXT_RUN_INDICATOR]
(
 [NEXT_RUN_INDICATOR]             varchar(1) NOT NULL ,
 [NEXT_RUN_INDICATOR_DESCRIPTION] varchar(100) NOT NULL ,

 CONSTRAINT [PK_NEXT_RUN_INDICATOR] PRIMARY KEY CLUSTERED ([NEXT_RUN_INDICATOR] ASC)
);
GO








-- ************************************** [dbo].[MODULE_TYPE]

CREATE TABLE [dbo].[MODULE_TYPE]
(
 [MODULE_TYPE_CODE]        varchar(100) NOT NULL ,
 [MODULE_TYPE_DESCRIPTION] varchar(1000) NOT NULL ,

 CONSTRAINT [PK_MODULE_TYPE] PRIMARY KEY CLUSTERED ([MODULE_TYPE_CODE] ASC)
);
GO








-- ************************************** [dbo].[LAYER]

CREATE TABLE [dbo].[LAYER]
(
 [LAYER_CODE]        varchar(100) NOT NULL ,
 [LAYER_DESCRIPTION] varchar(1000) NOT NULL ,

 CONSTRAINT [PK_LAYER] PRIMARY KEY CLUSTERED ([LAYER_CODE] ASC)
);
GO








-- ************************************** [dbo].[FREQUENCY]

CREATE TABLE [dbo].[FREQUENCY]
(
 [FREQUENCY_CODE]        varchar(100) NOT NULL ,
 [FREQUENCY_DESCRIPTION] varchar(1000) NOT NULL ,

 CONSTRAINT [PK_FREQUENCY] PRIMARY KEY CLUSTERED ([FREQUENCY_CODE] ASC)
);
GO








-- ************************************** [dbo].[EXECUTION_STATUS]

CREATE TABLE [dbo].[EXECUTION_STATUS]
(
 [EXECUTION_STATUS_CODE]        varchar(100) NOT NULL ,
 [EXECUTION_STATUS_DESCRIPTION] varchar(1000) NOT NULL ,

 CONSTRAINT [PK_EXECUTION_STATUS] PRIMARY KEY CLUSTERED ([EXECUTION_STATUS_CODE] ASC)
);
GO








-- ************************************** [dbo].[EVENT_TYPE]

CREATE TABLE [dbo].[EVENT_TYPE]
(
 [EVENT_TYPE_CODE]        varchar(100) NOT NULL ,
 [EVENT_TYPE_DESCRIPTION] varchar(1000) NOT NULL ,

 CONSTRAINT [PK_EVENT_TYPE] PRIMARY KEY CLUSTERED ([EVENT_TYPE_CODE] ASC)
);
GO








-- ************************************** [dbo].[ERROR_TYPE]

CREATE TABLE [dbo].[ERROR_TYPE]
(
 [ERROR_TYPE_CODE]        varchar(100) NOT NULL ,
 [ERROR_TYPE_DESCRIPTION] varchar(1000) NOT NULL ,

 CONSTRAINT [PK_ERROR_TYPE] PRIMARY KEY CLUSTERED ([ERROR_TYPE_CODE] ASC)
);
GO








-- ************************************** [dbo].[DATA_STORE_TYPE]

CREATE TABLE [dbo].[DATA_STORE_TYPE]
(
 [DATA_STORE_TYPE_CODE]        varchar(100) NOT NULL ,
 [DATA_STORE_TYPE_DESCRIPTION] varchar(1000) NOT NULL ,

 CONSTRAINT [PK_DATA_STORE_TYPE] PRIMARY KEY CLUSTERED ([DATA_STORE_TYPE_CODE] ASC)
);
GO








-- ************************************** [dbo].[DATA_AUDIT_TYPE]

CREATE TABLE [dbo].[DATA_AUDIT_TYPE]
(
 [DATA_AUDIT_TYPE_CODE]        varchar(100) NOT NULL ,
 [DATA_AUDIT_TYPE_DESCRIPTION] varchar(1000) NOT NULL ,
 [START_DATE_COLUMN_CODE]      varchar(100) NULL ,
 [END_DATE_COLUMN_CODE]        varchar(100) NULL ,
 [VERSION_DATE]                datetime NOT NULL CONSTRAINT [DF_DATA_AUDIT_TYPE_VERSION_DATE] DEFAULT (getdate()) ,
 [INACTIVE_INDICATOR]          varchar(1) NOT NULL CONSTRAINT [DF_DATA_AUDIT_TYPE_INACTIVE_INDICATOR] DEFAULT ('N') ,

 CONSTRAINT [PK_DATA_AUDIT_TYPE] PRIMARY KEY CLUSTERED ([DATA_AUDIT_TYPE_CODE] ASC)
);
GO








-- ************************************** [dbo].[ERROR_BITMAP]

CREATE TABLE [dbo].[ERROR_BITMAP]
(
 [ERROR_ID]          int NOT NULL ,
 [SEVERITY_CODE]     varchar(100) NOT NULL ,
 [ERROR_TYPE_CODE]   varchar(100) NOT NULL ,
 [ERROR_DESCRIPTION] varchar(4000) NOT NULL ,

 CONSTRAINT [PK_ERROR_BITMAP] PRIMARY KEY CLUSTERED ([ERROR_ID] ASC),
 CONSTRAINT [FK_ERROR_SEVERITY] FOREIGN KEY ([SEVERITY_CODE])  REFERENCES [dbo].[SEVERITY]([SEVERITY_CODE]),
 CONSTRAINT [FK_ERROR_TYPE] FOREIGN KEY ([ERROR_TYPE_CODE])  REFERENCES [dbo].[ERROR_TYPE]([ERROR_TYPE_CODE])
);
GO


--SKIP Index: [FK_ERROR_SEVERITY]

--SKIP Index: [FK_ERROR_TYPE]







-- ************************************** [dbo].[DATA_STORE]

CREATE TABLE [dbo].[DATA_STORE]
(
 [DATA_STORE_ID]            int IDENTITY (1, 1) NOT NULL ,
 [DATA_STORE_CODE]          varchar(100) NOT NULL ,
 [DATA_STORE_TYPE_CODE]     varchar(100) NOT NULL ,
 [DATA_STORE_DESCRIPTION]   varchar(1000) NOT NULL ,
 [ALLOW_TRUNCATE_INDICATOR] varchar(1) NOT NULL ,

 CONSTRAINT [PK_DATA_STORE] PRIMARY KEY CLUSTERED ([DATA_STORE_ID] ASC),
 CONSTRAINT [IX_DATA_STORE] UNIQUE NONCLUSTERED ([DATA_STORE_CODE] ASC),
 CONSTRAINT [FK_DATA_STORE_DATA_STORE_TYPE] FOREIGN KEY ([DATA_STORE_TYPE_CODE])  REFERENCES [dbo].[DATA_STORE_TYPE]([DATA_STORE_TYPE_CODE])
);
GO


--SKIP Index: [FK_DATA_STORE_TYPE]







-- ************************************** [dbo].[BATCH]

CREATE TABLE [dbo].[BATCH]
(
 [BATCH_ID]           int IDENTITY (1, 1) NOT NULL ,
 [BATCH_CODE]         varchar(100) NOT NULL ,
 [FREQUENCY_CODE]     varchar(100) NULL ,
 [BATCH_DESCRIPTION]  varchar(1000) NOT NULL ,
 [INACTIVE_INDICATOR] varchar(1) NOT NULL CONSTRAINT [DF_BATCH_INACTIVE_INDICATOR] DEFAULT ('N') ,

 CONSTRAINT [PK_BATCH] PRIMARY KEY CLUSTERED ([BATCH_ID] ASC),
 CONSTRAINT [IX_BATCH] UNIQUE NONCLUSTERED ([BATCH_CODE] ASC),
 CONSTRAINT [FK_BATCH_FREQUENCY] FOREIGN KEY ([FREQUENCY_CODE])  REFERENCES [dbo].[FREQUENCY]([FREQUENCY_CODE])
);
GO


--SKIP Index: [FK_BATCH_FREQUENCY]







-- ************************************** [dbo].[AREA]

CREATE TABLE [dbo].[AREA]
(
 [AREA_CODE]        varchar(100) NOT NULL ,
 [LAYER_CODE]       varchar(100) NOT NULL ,
 [AREA_DESCRIPTION] varchar(1000) NOT NULL ,

 CONSTRAINT [PK_AREA] PRIMARY KEY CLUSTERED ([AREA_CODE] ASC),
 CONSTRAINT [FK_AREA_LAYER] FOREIGN KEY ([LAYER_CODE])  REFERENCES [dbo].[LAYER]([LAYER_CODE])
);
GO


--SKIP Index: [FK_AREA]







-- ************************************** [dbo].[MODULE]

CREATE TABLE [dbo].[MODULE]
(
 [MODULE_ID]          int IDENTITY (1, 1) NOT NULL ,
 [AREA_CODE]          varchar(100) NOT NULL ,
 [MODULE_CODE]        varchar(100) NOT NULL ,
 [MODULE_DESCRIPTION] varchar(1000) NOT NULL ,
 [MODULE_TYPE_CODE]   varchar(100) NOT NULL ,
 [INACTIVE_INDICATOR] varchar(1) NOT NULL CONSTRAINT [DF_MODULE_INACTIVE_INDICATOR] DEFAULT ('N') ,
 [FREQUENCY_CODE]     varchar(100) NOT NULL ,

 CONSTRAINT [PK_MODULE] PRIMARY KEY CLUSTERED ([MODULE_ID] ASC),
 CONSTRAINT [IX_MODULE] UNIQUE NONCLUSTERED ([MODULE_CODE] ASC),
 CONSTRAINT [FK_MODULE_AREA] FOREIGN KEY ([AREA_CODE])  REFERENCES [dbo].[AREA]([AREA_CODE]),
 CONSTRAINT [FK_MODULE_TYPE] FOREIGN KEY ([MODULE_TYPE_CODE])  REFERENCES [dbo].[MODULE_TYPE]([MODULE_TYPE_CODE])
);
GO


--SKIP Index: [FK_MODULE_AREA]

--SKIP Index: [FK_MODULE_TYPE]







-- ************************************** [dbo].[DATA_AUDIT]

CREATE TABLE [dbo].[DATA_AUDIT]
(
 [DATA_STORE_ID]        int NOT NULL ,
 [PROCESSING_DATE]      datetime NOT NULL ,
 [DATA_AUDIT_TYPE_CODE] varchar(100) NOT NULL ,
 [RECORD_COUNT]         int NOT NULL ,
 [LOAD_TIMESTAMP]       datetime NOT NULL ,

 CONSTRAINT [PK_DATA_AUDIT] PRIMARY KEY CLUSTERED ([DATA_STORE_ID] ASC, [PROCESSING_DATE] ASC),
 CONSTRAINT [FK_DATA__STORE_DATA_AUDIT] FOREIGN KEY ([DATA_STORE_ID])  REFERENCES [dbo].[DATA_STORE]([DATA_STORE_ID]),
 CONSTRAINT [FK_DATA_AUDIT_DATA_AUDIT_TYPE] FOREIGN KEY ([DATA_AUDIT_TYPE_CODE])  REFERENCES [dbo].[DATA_AUDIT_TYPE]([DATA_AUDIT_TYPE_CODE])
);
GO


--SKIP Index: [FK_DATA_AUDIT_DATA_STORE]

--SKIP Index: [FK_DATA_AUDIT_TYPE]







-- ************************************** [dbo].[BATCH_INSTANCE]

CREATE TABLE [dbo].[BATCH_INSTANCE]
(
 [BATCH_INSTANCE_ID]         int IDENTITY (1, 1) NOT NULL ,
 [BATCH_ID]                  int NOT NULL ,
 [START_DATETIME]            datetime NOT NULL ,
 [END_DATETIME]              datetime NULL ,
 [PROCESSING_INDICATOR]      varchar(1) NULL ,
 [NEXT_RUN_INDICATOR]        varchar(1) NULL ,
 [EXECUTION_STATUS_CODE]     varchar(100) NOT NULL ,
 [BATCH_EXECUTION_SYSTEM_ID] varchar(100) NULL ,

 CONSTRAINT [PK_BATCH_INSTANCE] PRIMARY KEY CLUSTERED ([BATCH_INSTANCE_ID] ASC),
 CONSTRAINT [FK_BATCH_BATCH_INSTANCE] FOREIGN KEY ([BATCH_ID])  REFERENCES [dbo].[BATCH]([BATCH_ID]),
 CONSTRAINT [FK_BATCH_INSTANCE_EXECUTION_STATUS] FOREIGN KEY ([EXECUTION_STATUS_CODE])  REFERENCES [dbo].[EXECUTION_STATUS]([EXECUTION_STATUS_CODE]),
 CONSTRAINT [FK_BATCH_INSTANCE_NEXT_RUN_INDICATOR] FOREIGN KEY ([NEXT_RUN_INDICATOR])  REFERENCES [dbo].[NEXT_RUN_INDICATOR]([NEXT_RUN_INDICATOR]),
 CONSTRAINT [FK_BATCH_INSTANCE_PROCESSING_INDICATOR] FOREIGN KEY ([PROCESSING_INDICATOR])  REFERENCES [dbo].[PROCESSING_INDICATOR]([PROCESSING_INDICATOR])
);
GO


--SKIP Index: [FK_BATCH_INSTANCE_BATCH]

--SKIP Index: [FK_BATCH_INSTANCE_EXECUTION_STATUS_CODE]

--SKIP Index: [FK_BATCH_INSTANCE_NEXT_RUN_INDICATOR]

--SKIP Index: [FK_BATCH_INSTANCE_PROCESSING_INDICATOR]







-- ************************************** [dbo].[MODULE_PARAMETER]

CREATE TABLE [dbo].[MODULE_PARAMETER]
(
 [MODULE_ID]    int NOT NULL ,
 [PARAMETER_ID] int NOT NULL ,

 CONSTRAINT [PK_MODULE_PARAMETER] PRIMARY KEY CLUSTERED ([MODULE_ID] ASC, [PARAMETER_ID] ASC),
 CONSTRAINT [FK_MODULE_MODULE_PARAMETER] FOREIGN KEY ([PARAMETER_ID])  REFERENCES [dbo].[PARAMETER]([PARAMETER_ID]),
 CONSTRAINT [FK_MODULE_PARAMETER] FOREIGN KEY ([MODULE_ID])  REFERENCES [dbo].[MODULE]([MODULE_ID])
);
GO


--SKIP Index: [FK_MODULE_PARAMETER_MODULE]

--SKIP Index: [FK_MODULE_PARAMETER_PARAMETER]







-- ************************************** [dbo].[MODULE_INSTANCE]

CREATE TABLE [dbo].[MODULE_INSTANCE]
(
 [MODULE_INSTANCE_ID]         int IDENTITY (1, 1) NOT NULL ,
 [MODULE_ID]                  int NOT NULL ,
 [BATCH_INSTANCE_ID]          int NOT NULL ,
 [START_DATETIME]             datetime NOT NULL ,
 [END_DATETIME]               datetime NULL ,
 [PROCESSING_INDICATOR]       varchar(1) NULL ,
 [NEXT_RUN_INDICATOR]         varchar(1) NULL ,
 [EXECUTION_STATUS_CODE]      varchar(100) NOT NULL ,
 [MODULE_EXECUTION_SYSTEM_ID] varchar(100) NULL ,
 [ROWS_INPUT]                 int NULL ,
 [ROWS_INSERTED]              int NULL ,
 [ROWS_UPDATED]               int NULL ,
 [ROWS_DELETED]               int NULL ,
 [ROWS_DISCARDED]             int NULL ,
 [ROWS_REJECTED]              int NULL ,

 CONSTRAINT [PK_MODULE_INSTANCE] PRIMARY KEY CLUSTERED ([MODULE_INSTANCE_ID] ASC),
 CONSTRAINT [FK_MODULE_INSTANCE] FOREIGN KEY ([MODULE_ID])  REFERENCES [dbo].[MODULE]([MODULE_ID]),
 CONSTRAINT [FK_MODULE_INSTANCE_BATCH_INSTANCE] FOREIGN KEY ([BATCH_INSTANCE_ID])  REFERENCES [dbo].[BATCH_INSTANCE]([BATCH_INSTANCE_ID]),
 CONSTRAINT [FK_MODULE_INSTANCE_EXECUTION_STATUS] FOREIGN KEY ([EXECUTION_STATUS_CODE])  REFERENCES [dbo].[EXECUTION_STATUS]([EXECUTION_STATUS_CODE]),
 CONSTRAINT [FK_MODULE_INSTANCE_NEXT_RUN_INDICATOR] FOREIGN KEY ([NEXT_RUN_INDICATOR])  REFERENCES [dbo].[NEXT_RUN_INDICATOR]([NEXT_RUN_INDICATOR]),
 CONSTRAINT [FK_MODULE_INSTANCE_PROCESSING_INDICATOR] FOREIGN KEY ([PROCESSING_INDICATOR])  REFERENCES [dbo].[PROCESSING_INDICATOR]([PROCESSING_INDICATOR])
);
GO


--SKIP Index: [FK_MODULE_INSTANCE_BATCH_INSTANCE]

--SKIP Index: [FK_MODULE_INSTANCE_EXECUTION_STATUS_CODE]

--SKIP Index: [FK_MODULE_INSTANCE_MODULE]

--SKIP Index: [FK_MODULE_INSTANCE_NEXT_RUN_INDICATOR]

--SKIP Index: [FK_MODULE_INSTANCE_PROCESSING_INDICATOR]







-- ************************************** [dbo].[MODULE_DATA_STORE]

CREATE TABLE [dbo].[MODULE_DATA_STORE]
(
 [MODULE_ID]         int NOT NULL ,
 [DATA_STORE_ID]     int NOT NULL ,
 [RELATIONSHIP_TYPE] varchar(100) NOT NULL ,

 CONSTRAINT [PK_MODULE_DATA_STORE] PRIMARY KEY CLUSTERED ([MODULE_ID] ASC, [DATA_STORE_ID] ASC),
 CONSTRAINT [FK_DATA_STORE_MODULE_DATA_STORE] FOREIGN KEY ([DATA_STORE_ID])  REFERENCES [dbo].[DATA_STORE]([DATA_STORE_ID]),
 CONSTRAINT [FK_MODULE_MODULE_DATA_STORE] FOREIGN KEY ([MODULE_ID])  REFERENCES [dbo].[MODULE]([MODULE_ID])
);
GO


--SKIP Index: [FK_MODULE_DATA_STORE_DATA_STORE]

--SKIP Index: [FK_MODULE_DATA_STORE_MODULE]







-- ************************************** [dbo].[BATCH_MODULE]

CREATE TABLE [dbo].[BATCH_MODULE]
(
 [BATCH_ID]           int NOT NULL ,
 [MODULE_ID]          int NOT NULL ,
 [INACTIVE_INDICATOR] varchar(1) NOT NULL CONSTRAINT [DF_BATCH_MODULE_INACTIVE_INDICATOR] DEFAULT ('N') ,

 CONSTRAINT [PK_BATCH_MODULE] PRIMARY KEY CLUSTERED ([BATCH_ID] ASC, [MODULE_ID] ASC),
 CONSTRAINT [FK_BATCH_BATCH_MODULE] FOREIGN KEY ([BATCH_ID])  REFERENCES [dbo].[BATCH]([BATCH_ID]),
 CONSTRAINT [FK_MODULE_BATCH_MODULE] FOREIGN KEY ([MODULE_ID])  REFERENCES [dbo].[MODULE]([MODULE_ID])
);
GO


--SKIP Index: [FK_BATCH_MODULE_BATCH]

--SKIP Index: [FK_BATCH_MODULE_MODULE]







-- ************************************** [dbo].[SOURCE_CONTROL]

CREATE TABLE [dbo].[SOURCE_CONTROL]
(
 [MODULE_SOURCE_CONTROL_ID]  int IDENTITY (1, 1) NOT NULL ,
 [MODULE_INSTANCE_ID]        int NOT NULL ,
 [INSERT_DATETIME]           datetime2(7) NULL ,
 [INTERVAL_DATETIME]         datetime2(7) NULL ,
 [INTERVAL_START_DATETIME]   datetime2(7) NULL ,
 [INTERVAL_END_DATETIME]     datetime2(7) NULL ,
 [INTERVAL_START_IDENTIFIER] bigint NULL ,
 [INTERVAL_END_IDENTIFIER]   bigint NULL ,

 CONSTRAINT [PK_SOURCE_CONTROL] PRIMARY KEY CLUSTERED ([MODULE_SOURCE_CONTROL_ID] ASC),
 CONSTRAINT [FK_MODULE_INSTANCE_SOURCE_CONTROL] FOREIGN KEY ([MODULE_INSTANCE_ID])  REFERENCES [dbo].[MODULE_INSTANCE]([MODULE_INSTANCE_ID])
);
GO


--SKIP Index: [FK_SOURCE_CONTROL_MODULE_INSTANCE]







-- ************************************** [dbo].[EVENT_LOG]

CREATE TABLE [dbo].[EVENT_LOG]
(
 [EVENT_ID]                  int IDENTITY (1, 1) NOT NULL ,
 [BATCH_INSTANCE_ID]         int NOT NULL ,
 [MODULE_INSTANCE_ID]        int NOT NULL ,
 [EVENT_TYPE_CODE]           varchar(100) NOT NULL ,
 [EVENT_DATETIME]            datetime NOT NULL ,
 [EVENT_RETURN_CODE_DETAILS] varchar(1000) NOT NULL ,
 [EVENT_DETAIL]              varchar(4000) NOT NULL ,
 [ERROR_BITMAP]              numeric(20,0) NULL ,

 CONSTRAINT [PK_EVENT_LOG] PRIMARY KEY CLUSTERED ([EVENT_ID] ASC),
 CONSTRAINT [FK_BATCH_EVENT] FOREIGN KEY ([BATCH_INSTANCE_ID])  REFERENCES [dbo].[BATCH_INSTANCE]([BATCH_INSTANCE_ID]),
 CONSTRAINT [FK_EVENT_LOG_EVENT_TYPE] FOREIGN KEY ([EVENT_TYPE_CODE])  REFERENCES [dbo].[EVENT_TYPE]([EVENT_TYPE_CODE]),
 CONSTRAINT [FK_MODULE_INSTANCE_EVENT_LOG] FOREIGN KEY ([MODULE_INSTANCE_ID])  REFERENCES [dbo].[MODULE_INSTANCE]([MODULE_INSTANCE_ID])
);
GO


--SKIP Index: [FK_EVENT_LOG_BATCH_INSTANCE]

--SKIP Index: [FK_EVENT_LOG_MODULE_INSTANCE]

--SKIP Index: [FK_EVENT_LOG_TYPE]







