-- ****************** SqlDBM: Microsoft SQL Server ******************
-- ******************************************************************

DROP TABLE [dbo].[SOURCE_CONTROL];
GO


DROP TABLE [dbo].[EVENT_LOG];
GO


DROP TABLE [dbo].[MODULE_PARAMETER];
GO


DROP TABLE [dbo].[MODULE_INSTANCE];
GO


DROP TABLE [dbo].[MODULE_DATA_STORE];
GO


DROP TABLE [dbo].[BATCH_MODULE];
GO


DROP TABLE [dbo].[MODULE];
GO


DROP TABLE [dbo].[DATA_AUDIT];
GO


DROP TABLE [dbo].[BATCH_INSTANCE];
GO


DROP TABLE [dbo].[ERROR_BITMAP];
GO


DROP TABLE [dbo].[DATA_STORE];
GO


DROP TABLE [dbo].[BATCH];
GO


DROP TABLE [dbo].[AREA];
GO


DROP TABLE [dbo].[VERSION];
GO


DROP TABLE [dbo].[SEVERITY];
GO


DROP TABLE [dbo].[RECORD_SOURCE];
GO


DROP TABLE [dbo].[PROCESSING_INDICATOR];
GO


DROP TABLE [dbo].[PARAMETER];
GO


DROP TABLE [dbo].[NEXT_RUN_INDICATOR];
GO


DROP TABLE [dbo].[MODULE_TYPE];
GO


DROP TABLE [dbo].[LAYER];
GO


DROP TABLE [dbo].[FREQUENCY];
GO


DROP TABLE [dbo].[EXECUTION_STATUS];
GO


DROP TABLE [dbo].[EVENT_TYPE];
GO


DROP TABLE [dbo].[ERROR_TYPE];
GO


DROP TABLE [dbo].[DATA_STORE_TYPE];
GO


DROP TABLE [dbo].[DATA_AUDIT_TYPE];
GO


--************************************** [dbo].[VERSION]

CREATE TABLE [dbo].[VERSION]
(
 [VERSION_ID]   VARCHAR(100) NOT NULL ,
 [COMMENTS]     VARCHAR(4000) NOT NULL ,
 [RELEASE_DATE] DATETIME NOT NULL ,

 CONSTRAINT [PK_OMD_VERSION] PRIMARY KEY CLUSTERED ([VERSION_ID] ASC)
);
GO



--************************************** [dbo].[SEVERITY]

CREATE TABLE [dbo].[SEVERITY]
(
 [SEVERITY_CODE]        VARCHAR(100) NOT NULL ,
 [SEVERITY_DESCRIPTION] VARCHAR(1000) NOT NULL ,

 CONSTRAINT [PK__OMD_SEVE__C3511CE9E255BF9B] PRIMARY KEY CLUSTERED ([SEVERITY_CODE] ASC)
);
GO



--************************************** [dbo].[RECORD_SOURCE]

CREATE TABLE [dbo].[RECORD_SOURCE]
(
 [RECORD_SOURCE_ID]   INT IDENTITY (1, 1) NOT NULL ,
 [RECORD_SOURCE_CODE] VARCHAR(20) NOT NULL ,

 CONSTRAINT [PK__OMD_RECO__011E6E3AC027CD84] PRIMARY KEY CLUSTERED ([RECORD_SOURCE_ID] ASC)
);
GO



--************************************** [dbo].[PROCESSING_INDICATOR]

CREATE TABLE [dbo].[PROCESSING_INDICATOR]
(
 [PROCESSING_INDICATOR]             VARCHAR(1) NOT NULL ,
 [PROCESSING_INDICATOR_DESCRIPTION] VARCHAR(100) NOT NULL ,

 CONSTRAINT [PK__OMD_PROC__8BC2AEA68785130F] PRIMARY KEY CLUSTERED ([PROCESSING_INDICATOR] ASC)
);
GO



--************************************** [dbo].[PARAMETER]

CREATE TABLE [dbo].[PARAMETER]
(
 [PARAMETER_ID]          INT IDENTITY (1, 1) NOT NULL ,
 [PARAMETER_DESCRIPTION] VARCHAR(1000) NOT NULL ,
 [PARAMETER_KEY_CODE]    VARCHAR(100) NOT NULL ,
 [PARAMETER_VALUE_CODE]  VARCHAR(100) NOT NULL ,

 CONSTRAINT [PK__OMD_PARA__B7867DAC85DD73F1] PRIMARY KEY CLUSTERED ([PARAMETER_ID] ASC)
);
GO



--************************************** [dbo].[NEXT_RUN_INDICATOR]

CREATE TABLE [dbo].[NEXT_RUN_INDICATOR]
(
 [NEXT_RUN_INDICATOR]             VARCHAR(1) NOT NULL ,
 [NEXT_RUN_INDICATOR_DESCRIPTION] VARCHAR(100) NOT NULL ,

 CONSTRAINT [PK__OMD_NEXT__EFC70D970AD238C4] PRIMARY KEY CLUSTERED ([NEXT_RUN_INDICATOR] ASC)
);
GO



--************************************** [dbo].[MODULE_TYPE]

CREATE TABLE [dbo].[MODULE_TYPE]
(
 [MODULE_TYPE_CODE]        VARCHAR(100) NOT NULL ,
 [MODULE_TYPE_DESCRIPTION] VARCHAR(1000) NOT NULL ,

 CONSTRAINT [PK__OMD_MODU__C2CCE8B7C5191362] PRIMARY KEY CLUSTERED ([MODULE_TYPE_CODE] ASC)
);
GO



--************************************** [dbo].[LAYER]

CREATE TABLE [dbo].[LAYER]
(
 [LAYER_CODE]        VARCHAR(100) NOT NULL ,
 [LAYER_DESCRIPTION] VARCHAR(1000) NOT NULL ,

 CONSTRAINT [PK__OMD_LAYE__1478407216559982] PRIMARY KEY CLUSTERED ([LAYER_CODE] ASC)
);
GO



--************************************** [dbo].[FREQUENCY]

CREATE TABLE [dbo].[FREQUENCY]
(
 [FREQUENCY_CODE]        VARCHAR(100) NOT NULL ,
 [FREQUENCY_DESCRIPTION] VARCHAR(1000) NOT NULL ,

 CONSTRAINT [PK__OMD_FREQ__9E30850DB092A34C] PRIMARY KEY CLUSTERED ([FREQUENCY_CODE] ASC)
);
GO



--************************************** [dbo].[EXECUTION_STATUS]

CREATE TABLE [dbo].[EXECUTION_STATUS]
(
 [EXECUTION_STATUS_CODE]        VARCHAR(100) NOT NULL ,
 [EXECUTION_STATUS_DESCRIPTION] VARCHAR(1000) NOT NULL ,

 CONSTRAINT [PK__OMD_EXEC__ED13D259DDCCB6DE] PRIMARY KEY CLUSTERED ([EXECUTION_STATUS_CODE] ASC)
);
GO



--************************************** [dbo].[EVENT_TYPE]

CREATE TABLE [dbo].[EVENT_TYPE]
(
 [EVENT_TYPE_CODE]        VARCHAR(100) NOT NULL ,
 [EVENT_TYPE_DESCRIPTION] VARCHAR(1000) NOT NULL ,

 CONSTRAINT [PK__OMD_EVEN__C2F1A77ED7DF7826] PRIMARY KEY CLUSTERED ([EVENT_TYPE_CODE] ASC)
);
GO



--************************************** [dbo].[ERROR_TYPE]

CREATE TABLE [dbo].[ERROR_TYPE]
(
 [ERROR_TYPE_CODE]        VARCHAR(100) NOT NULL ,
 [ERROR_TYPE_DESCRIPTION] VARCHAR(1000) NOT NULL ,

 CONSTRAINT [PK__OMD_ERRO__838DB8EDF80917FE] PRIMARY KEY CLUSTERED ([ERROR_TYPE_CODE] ASC)
);
GO



--************************************** [dbo].[DATA_STORE_TYPE]

CREATE TABLE [dbo].[DATA_STORE_TYPE]
(
 [DATA_STORE_TYPE_CODE]        VARCHAR(100) NOT NULL ,
 [DATA_STORE_TYPE_DESCRIPTION] VARCHAR(1000) NOT NULL ,

 CONSTRAINT [PK__OMD_DATA__047F92468D98BCEA] PRIMARY KEY CLUSTERED ([DATA_STORE_TYPE_CODE] ASC)
);
GO



--************************************** [dbo].[DATA_AUDIT_TYPE]

CREATE TABLE [dbo].[DATA_AUDIT_TYPE]
(
 [DATA_AUDIT_TYPE_CODE]        VARCHAR(100) NOT NULL ,
 [DATA_AUDIT_TYPE_DESCRIPTION] VARCHAR(1000) NOT NULL ,
 [START_DATE_COLUMN_CODE]      VARCHAR(100) NULL ,
 [END_DATE_COLUMN_CODE]        VARCHAR(100) NULL ,
 [VERSION_DATE]                DATETIME NOT NULL CONSTRAINT [DF_DATA_AUDIT_TYPE_VERSION_DATE] DEFAULT (getdate()) ,
 [INACTIVE_INDICATOR]          VARCHAR(1) NOT NULL CONSTRAINT [DF_DATA_AUDIT_TYPE_INACTIVE_INDICATOR] DEFAULT ('N') ,

 CONSTRAINT [PK__OMD_DATA__3BEFF6F9372D58D4] PRIMARY KEY CLUSTERED ([DATA_AUDIT_TYPE_CODE] ASC)
);
GO



--************************************** [dbo].[ERROR_BITMAP]

CREATE TABLE [dbo].[ERROR_BITMAP]
(
 [ERROR_ID]          INT NOT NULL ,
 [SEVERITY_CODE]     VARCHAR(100) NOT NULL ,
 [ERROR_TYPE_CODE]   VARCHAR(100) NOT NULL ,
 [ERROR_DESCRIPTION] VARCHAR(4000) NOT NULL ,

 CONSTRAINT [PK__OMD_ERRO__88C516E96DD88823] PRIMARY KEY CLUSTERED ([ERROR_ID] ASC),
 CONSTRAINT [FK__OMD_ERROR__ERROR__6D0D32F4] FOREIGN KEY ([ERROR_TYPE_CODE])
  REFERENCES [dbo].[ERROR_TYPE]([ERROR_TYPE_CODE]),
 CONSTRAINT [FK__OMD_ERROR__SEVER__6C190EBB] FOREIGN KEY ([SEVERITY_CODE])
  REFERENCES [dbo].[SEVERITY]([SEVERITY_CODE])
);
GO


--SKIP Index: [IFK__OMD_ERROR__ERROR__6D0D32F4]

--SKIP Index: [IFK__OMD_ERROR__SEVER__6C190EBB]


--************************************** [dbo].[DATA_STORE]

CREATE TABLE [dbo].[DATA_STORE]
(
 [DATA_STORE_ID]            INT IDENTITY (1, 1) NOT NULL ,
 [DATA_STORE_CODE]          VARCHAR(100) NOT NULL ,
 [DATA_STORE_TYPE_CODE]     VARCHAR(100) NOT NULL ,
 [DATA_STORE_DESCRIPTION]   VARCHAR(1000) NOT NULL ,
 [ALLOW_TRUNCATE_INDICATOR] VARCHAR(1) NOT NULL ,

 CONSTRAINT [PK__OMD_DATA__3A370D03D0D2ED62] PRIMARY KEY CLUSTERED ([DATA_STORE_ID] ASC),
 CONSTRAINT [IX_OMD_DATA_STORE] UNIQUE NONCLUSTERED ([DATA_STORE_CODE] ASC),
 CONSTRAINT [FK_DATA_STORE_DATA_STORE_TYPE] FOREIGN KEY ([DATA_STORE_TYPE_CODE])
  REFERENCES [dbo].[DATA_STORE_TYPE]([DATA_STORE_TYPE_CODE])
);
GO


--SKIP Index: [IFK__OMD_DATA___DATA___7C4F7684]


--************************************** [dbo].[BATCH]

CREATE TABLE [dbo].[BATCH]
(
 [BATCH_ID]           INT IDENTITY (1, 1) NOT NULL ,
 [BATCH_CODE]         VARCHAR(100) NOT NULL ,
 [FREQUENCY_CODE]     VARCHAR(100) NULL ,
 [BATCH_DESCRIPTION]  VARCHAR(1000) NOT NULL ,
 [INACTIVE_INDICATOR] VARCHAR(1) NOT NULL CONSTRAINT [DF_BATCH_INACTIVE_INDICATOR] DEFAULT ('N') ,

 CONSTRAINT [PK__OMD_BATC__2172E4632AF40DAC] PRIMARY KEY CLUSTERED ([BATCH_ID] ASC),
 CONSTRAINT [IX_OMD_BATCH] UNIQUE NONCLUSTERED ([BATCH_CODE] ASC),
 CONSTRAINT [FK__BATCH_FREQUENCY] FOREIGN KEY ([FREQUENCY_CODE])
  REFERENCES [dbo].[FREQUENCY]([FREQUENCY_CODE])
);
GO


--SKIP Index: [IFK__OMD_BATCH__FREQU__619B8048]


--************************************** [dbo].[AREA]

CREATE TABLE [dbo].[AREA]
(
 [AREA_CODE]        VARCHAR(100) NOT NULL ,
 [LAYER_CODE]       VARCHAR(100) NOT NULL ,
 [AREA_DESCRIPTION] VARCHAR(1000) NOT NULL ,

 CONSTRAINT [PK__OMD_AREA__FC7CF809DEF8FCF0] PRIMARY KEY CLUSTERED ([AREA_CODE] ASC),
 CONSTRAINT [FK__AREA_LAYER] FOREIGN KEY ([LAYER_CODE])
  REFERENCES [dbo].[LAYER]([LAYER_CODE])
);
GO


--SKIP Index: [IFK__OMD_AREA__LAYER___60A75C0F]


--************************************** [dbo].[MODULE]

CREATE TABLE [dbo].[MODULE]
(
 [MODULE_ID]          INT IDENTITY (1, 1) NOT NULL ,
 [AREA_CODE]          VARCHAR(100) NOT NULL ,
 [MODULE_CODE]        VARCHAR(100) NOT NULL ,
 [MODULE_DESCRIPTION] VARCHAR(1000) NOT NULL ,
 [MODULE_TYPE_CODE]   VARCHAR(100) NOT NULL ,
 [INACTIVE_INDICATOR] VARCHAR(1) NOT NULL CONSTRAINT [DF_MODULE_INACTIVE_INDICATOR] DEFAULT ('N') ,
 [FREQUENCY_CODE]     VARCHAR(100) NOT NULL ,

 CONSTRAINT [PK__OMD_MODU__238A8246A664CFA9] PRIMARY KEY CLUSTERED ([MODULE_ID] ASC),
 CONSTRAINT [IX_OMD_MODULE] UNIQUE NONCLUSTERED ([MODULE_CODE] ASC),
 CONSTRAINT [FK_MODULE_AREA] FOREIGN KEY ([AREA_CODE])
  REFERENCES [dbo].[AREA]([AREA_CODE]),
 CONSTRAINT [FK__OMD_MODUL__MODUL__71D1E811] FOREIGN KEY ([MODULE_TYPE_CODE])
  REFERENCES [dbo].[MODULE_TYPE]([MODULE_TYPE_CODE])
);
GO


--SKIP Index: [IFK__OMD_MODUL__AREA___70DDC3D8]

--SKIP Index: [IFK__OMD_MODUL__MODUL__71D1E811]


--************************************** [dbo].[DATA_AUDIT]

CREATE TABLE [dbo].[DATA_AUDIT]
(
 [DATA_STORE_ID]        INT NOT NULL ,
 [PROCESSING_DATE]      DATETIME NOT NULL ,
 [DATA_AUDIT_TYPE_CODE] VARCHAR(100) NOT NULL ,
 [RECORD_COUNT]         INT NOT NULL ,
 [LOAD_TIMESTAMP]       DATETIME NOT NULL ,

 CONSTRAINT [PK__OMD_DATA__3C15B8B287399D8D] PRIMARY KEY CLUSTERED ([DATA_STORE_ID] ASC, [PROCESSING_DATE] ASC),
 CONSTRAINT [FK__DATA__STORE_DATA_AUDIT] FOREIGN KEY ([DATA_STORE_ID])
  REFERENCES [dbo].[DATA_STORE]([DATA_STORE_ID]),
 CONSTRAINT [FK__DATA_AUDIT_DATA_AUDIT_TYPE] FOREIGN KEY ([DATA_AUDIT_TYPE_CODE])
  REFERENCES [dbo].[DATA_AUDIT_TYPE]([DATA_AUDIT_TYPE_CODE])
);
GO


--SKIP Index: [IFK__OMD_DATA___DATA___7A672E12]

--SKIP Index: [IFK__OMD_DATA___DATA___7B5B524B]


--************************************** [dbo].[BATCH_INSTANCE]

CREATE TABLE [dbo].[BATCH_INSTANCE]
(
 [BATCH_INSTANCE_ID]         INT IDENTITY (1, 1) NOT NULL ,
 [BATCH_ID]                  INT NOT NULL ,
 [START_DATETIME]            DATETIME NOT NULL ,
 [END_DATETIME]              DATETIME NULL ,
 [PROCESSING_INDICATOR]      VARCHAR(1) NULL ,
 [NEXT_RUN_INDICATOR]        VARCHAR(1) NULL ,
 [EXECUTION_STATUS_CODE]     VARCHAR(100) NOT NULL ,
 [BATCH_EXECUTION_SYSTEM_ID] VARCHAR(100) NULL ,

 CONSTRAINT [PK__OMD_BATC__242BFEFCB9537107] PRIMARY KEY CLUSTERED ([BATCH_INSTANCE_ID] ASC),
 CONSTRAINT [FK_BATCH_BATCH_INSTANCE] FOREIGN KEY ([BATCH_ID])
  REFERENCES [dbo].[BATCH]([BATCH_ID]),
 CONSTRAINT [FK__BATCH_INSTANCE_EXECUTION_STATUS] FOREIGN KEY ([EXECUTION_STATUS_CODE])
  REFERENCES [dbo].[EXECUTION_STATUS]([EXECUTION_STATUS_CODE]),
 CONSTRAINT [FK__BATCH_INSTANCE_NEXT_RUN_INDICATOR] FOREIGN KEY ([NEXT_RUN_INDICATOR])
  REFERENCES [dbo].[NEXT_RUN_INDICATOR]([NEXT_RUN_INDICATOR]),
 CONSTRAINT [FK__BATCH_INSTANCE_PROCESSING_INDICATOR] FOREIGN KEY ([PROCESSING_INDICATOR])
  REFERENCES [dbo].[PROCESSING_INDICATOR]([PROCESSING_INDICATOR])
);
GO


--SKIP Index: [IFK__OMD_BATCH__BATCH__628FA481]

--SKIP Index: [IFK__OMD_BATCH__EXECU__6383C8BA]

--SKIP Index: [IFK__OMD_BATCH__NEXT___656C112C]

--SKIP Index: [IFK__OMD_BATCH__PROCE__6477ECF3]


--************************************** [dbo].[MODULE_PARAMETER]

CREATE TABLE [dbo].[MODULE_PARAMETER]
(
 [MODULE_ID]    INT NOT NULL ,
 [PARAMETER_ID] INT NOT NULL ,

 CONSTRAINT [PK__OMD_MODU__F8F2E59C4C8F1822] PRIMARY KEY CLUSTERED ([MODULE_ID] ASC, [PARAMETER_ID] ASC),
 CONSTRAINT [FK__MODULE_MODULE_PARAMETER] FOREIGN KEY ([MODULE_ID])
  REFERENCES [dbo].[MODULE]([MODULE_ID]),
 CONSTRAINT [FK__MODULE_PARAMETER_PARAMETER] FOREIGN KEY ([PARAMETER_ID])
  REFERENCES [dbo].[PARAMETER]([PARAMETER_ID])
);
GO


--SKIP Index: [IFK__OMD_MODUL__MODUL__778AC167]

--SKIP Index: [IFK__OMD_MODUL__PARAM__787EE5A0]


--************************************** [dbo].[MODULE_INSTANCE]

CREATE TABLE [dbo].[MODULE_INSTANCE]
(
 [MODULE_INSTANCE_ID]         INT IDENTITY (1, 1) NOT NULL ,
 [MODULE_ID]                  INT NOT NULL ,
 [BATCH_INSTANCE_ID]          INT NOT NULL ,
 [START_DATETIME]             DATETIME NOT NULL ,
 [END_DATETIME]               DATETIME NULL ,
 [PROCESSING_INDICATOR]       VARCHAR(1) NULL ,
 [NEXT_RUN_INDICATOR]         VARCHAR(1) NULL ,
 [EXECUTION_STATUS_CODE]      VARCHAR(100) NOT NULL ,
 [MODULE_EXECUTION_SYSTEM_ID] VARCHAR(100) NULL ,
 [ROWS_INPUT]                 INT NULL ,
 [ROWS_INSERTED]              INT NULL ,
 [ROWS_UPDATED]               INT NULL ,
 [ROWS_DELETED]               INT NULL ,
 [ROWS_DISCARDED]             INT NULL ,
 [ROWS_REJECTED]              INT NULL ,

 CONSTRAINT [PK__OMD_MODU__8AB2AAAD19BC1CF1] PRIMARY KEY CLUSTERED ([MODULE_INSTANCE_ID] ASC),
 CONSTRAINT [FK__MODULE_INSTANCE_BATCH_INSTANCE] FOREIGN KEY ([BATCH_INSTANCE_ID])
  REFERENCES [dbo].[BATCH_INSTANCE]([BATCH_INSTANCE_ID]),
 CONSTRAINT [FK__MODULE_INSTANCE_EXECUTION_STATUS] FOREIGN KEY ([EXECUTION_STATUS_CODE])
  REFERENCES [dbo].[EXECUTION_STATUS]([EXECUTION_STATUS_CODE]),
 CONSTRAINT [FK__OMD_MODUL__MODUL__73BA3083] FOREIGN KEY ([MODULE_ID])
  REFERENCES [dbo].[MODULE]([MODULE_ID]),
 CONSTRAINT [FK__MODULE_INSTANCE_NEXT_RUN_INDICATOR] FOREIGN KEY ([NEXT_RUN_INDICATOR])
  REFERENCES [dbo].[NEXT_RUN_INDICATOR]([NEXT_RUN_INDICATOR]),
 CONSTRAINT [FK_MODULE_INSTANCE_PROCESSING_INDICATOR] FOREIGN KEY ([PROCESSING_INDICATOR])
  REFERENCES [dbo].[PROCESSING_INDICATOR]([PROCESSING_INDICATOR])
);
GO


--SKIP Index: [IFK__OMD_MODUL__BATCH__72C60C4A]

--SKIP Index: [IFK__OMD_MODUL__EXECU__74AE54BC]

--SKIP Index: [IFK__OMD_MODUL__MODUL__73BA3083]

--SKIP Index: [IFK__OMD_MODUL__NEXT___76969D2E]

--SKIP Index: [IFK__OMD_MODUL__PROCE__75A278F5]


--************************************** [dbo].[MODULE_DATA_STORE]

CREATE TABLE [dbo].[MODULE_DATA_STORE]
(
 [MODULE_ID]         INT NOT NULL ,
 [DATA_STORE_ID]     INT NOT NULL ,
 [RELATIONSHIP_TYPE] VARCHAR(100) NOT NULL ,

 CONSTRAINT [PK__OMD_MODU__0029F296C8D723E3] PRIMARY KEY CLUSTERED ([MODULE_ID] ASC, [DATA_STORE_ID] ASC),
 CONSTRAINT [FK__DATA_STORE_MODULE_DATA_STORE] FOREIGN KEY ([DATA_STORE_ID])
  REFERENCES [dbo].[DATA_STORE]([DATA_STORE_ID]),
 CONSTRAINT [FK__MODULE_MODULE_DATA_STORE] FOREIGN KEY ([MODULE_ID])
  REFERENCES [dbo].[MODULE]([MODULE_ID])
);
GO


--SKIP Index: [IFK__OMD_MODUL__DATA___00200768]

--SKIP Index: [IFK__OMD_MODUL__MODUL__7F2BE32F]


--************************************** [dbo].[BATCH_MODULE]

CREATE TABLE [dbo].[BATCH_MODULE]
(
 [BATCH_ID]           INT NOT NULL ,
 [MODULE_ID]          INT NOT NULL ,
 [INACTIVE_INDICATOR] VARCHAR(1) NOT NULL CONSTRAINT [DF_BATCH_MODULE_INACTIVE_INDICATOR] DEFAULT ('N') ,

 CONSTRAINT [PK__OMD_BATC__534A4C47E0EB292E] PRIMARY KEY CLUSTERED ([BATCH_ID] ASC, [MODULE_ID] ASC),
 CONSTRAINT [FK_BATCH_BATCH_MODULE] FOREIGN KEY ([BATCH_ID])
  REFERENCES [dbo].[BATCH]([BATCH_ID]),
 CONSTRAINT [FK__MODULE_BATCH_MODULE] FOREIGN KEY ([MODULE_ID])
  REFERENCES [dbo].[MODULE]([MODULE_ID])
);
GO


--SKIP Index: [IFK__OMD_BATCH__BATCH__66603565]

--SKIP Index: [IFK__OMD_BATCH__MODUL__6754599E]


--************************************** [dbo].[SOURCE_CONTROL]

CREATE TABLE [dbo].[SOURCE_CONTROL]
(
 [MODULE_SOURCE_CONTROL_ID]  INT IDENTITY (1, 1) NOT NULL ,
 [MODULE_INSTANCE_ID]        INT NOT NULL ,
 [INSERT_DATETIME]           DATETIME2(7) NULL ,
 [INTERVAL_DATETIME]         DATETIME2(7) NULL ,
 [INTERVAL_START_DATETIME]   DATETIME2(7) NULL ,
 [INTERVAL_END_DATETIME]     DATETIME2(7) NULL ,
 [INTERVAL_START_IDENTIFIER] BIGINT NULL ,
 [INTERVAL_END_IDENTIFIER]   BIGINT NULL ,

 CONSTRAINT [PK__OMD_SOUR__9C1A2D6EC058C131] PRIMARY KEY CLUSTERED ([MODULE_SOURCE_CONTROL_ID] ASC),
 CONSTRAINT [FK__MODULE_INSTANCE_SOURCE_CONTROL] FOREIGN KEY ([MODULE_INSTANCE_ID])
  REFERENCES [dbo].[MODULE_INSTANCE]([MODULE_INSTANCE_ID])
);
GO


--SKIP Index: [IFK__OMD_SOURC__MODUL__67DE6983]


--************************************** [dbo].[EVENT_LOG]

CREATE TABLE [dbo].[EVENT_LOG]
(
 [EVENT_ID]                  INT IDENTITY (1, 1) NOT NULL ,
 [BATCH_INSTANCE_ID]         INT NOT NULL ,
 [MODULE_INSTANCE_ID]        INT NOT NULL ,
 [EVENT_TYPE_CODE]           VARCHAR(100) NOT NULL ,
 [EVENT_DATETIME]            DATETIME NOT NULL ,
 [EVENT_RETURN_CODE_DETAILS] VARCHAR(1000) NOT NULL ,
 [EVENT_DETAIL]              VARCHAR(4000) NOT NULL ,
 [ERROR_BITMAP]              NUMERIC(20,0) NULL ,

 CONSTRAINT [PK__OMD_EVEN__241A510C77CC0ECA] PRIMARY KEY CLUSTERED ([EVENT_ID] ASC),
 CONSTRAINT [FK__OMD_EVENT__BATCH__6E01572D] FOREIGN KEY ([BATCH_INSTANCE_ID])
  REFERENCES [dbo].[BATCH_INSTANCE]([BATCH_INSTANCE_ID]),
 CONSTRAINT [FK__EVENT_LOG_EVENT_TYPE] FOREIGN KEY ([EVENT_TYPE_CODE])
  REFERENCES [dbo].[EVENT_TYPE]([EVENT_TYPE_CODE]),
 CONSTRAINT [FK__MODULE_INSTANCE_EVENT_LOG] FOREIGN KEY ([MODULE_INSTANCE_ID])
  REFERENCES [dbo].[MODULE_INSTANCE]([MODULE_INSTANCE_ID])
);
GO


--SKIP Index: [IFK__OMD_EVENT__BATCH__6E01572D]

--SKIP Index: [IFK__OMD_EVENT__EVENT__6EF57B66]

--SKIP Index: [IFK__OMD_EVENT__MODUL__6FE99F9F]


